### ISSUE TITLE
跑services/app.py报错，提示显存不足

### ISSUE THREAD

**Issue by lyb19930105** [OptimalScale/LMFlow#146]
(lmflow) ocr@ocr-desktop:~/yab/test/LMFlow/service$ python3 app.py 

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
/home/ocr/.local/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: /home/ocr/anaconda3/envs/lmflow did not contain libcudart.so as expected! Searching further paths...
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 114
CUDA SETUP: Loading binary /home/ocr/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda114.so...
[2023-04-06 15:24:12,029] [INFO] [comm.py:634:init_distributed] Not using the DeepSpeed or dist launchers, attempting to detect MPI environment...
[2023-04-06 15:24:12,198] [INFO] [comm.py:688:mpi_discovery] Discovered MPI settings of world_rank=0, local_rank=0, world_size=1, master_addr=192.168.1.176, master_port=29500
[2023-04-06 15:24:12,198] [INFO] [comm.py:652:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[2023-04-06 15:24:12,211] [INFO] [logging.py:93:log_dist] [Rank 0] DeepSpeed info: version=0.8.3, git-hash=unknown, git-branch=unknown
Traceback (most recent call last):
  File "app.py", line 34, in <module>
    model = AutoModel.get_model(model_args, tune_strategy="none", ds_config=ds_config)
  File "/home/ocr/yab/test/LMFlow/src/lmflow/models/auto_model.py", line 14, in get_model
    return HFDecoderModel(model_args, *args, **kwargs)
  File "/home/ocr/yab/test/LMFlow/src/lmflow/models/hf_decoder_model.py", line 224, in __init__
    self.ds_engine = deepspeed.initialize(model=self.backend_model, config_params=ds_config)[0]
  File "/home/ocr/anaconda3/envs/lmflow/lib/python3.8/site-packages/deepspeed/__init__.py", line 125, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/ocr/anaconda3/envs/lmflow/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 297, in __init__
    self._configure_distributed_model(model)
  File "/home/ocr/anaconda3/envs/lmflow/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1135, in _configure_distributed_model
    self.module.half()
  File "/home/ocr/anaconda3/envs/lmflow/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1871, in half
    return super().half(*args)
  File "/home/ocr/anaconda3/envs/lmflow/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1001, in half
    return self._apply(lambda t: t.half() if t.is_floating_point() else t)
  File "/home/ocr/anaconda3/envs/lmflow/lib/python3.8/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/ocr/anaconda3/envs/lmflow/lib/python3.8/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/ocr/anaconda3/envs/lmflow/lib/python3.8/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/home/ocr/anaconda3/envs/lmflow/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1001, in <lambda>
    return self._apply(lambda t: t.half() if t.is_floating_point() else t)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 246.00 MiB (GPU 0; 10.75 GiB total capacity; 10.13 GiB already allocated; 70.31 MiB free; 10.14 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

我实验显卡用的是GeForce RTX 2080 Ti，显存11G，之前加载huggingface上面的chainyo/alpaca-lora-7b模型都没问题，为啥加载services/app.py里更小的OptimalScale/gpt-neo2.7B-inst-tuning就报错了？

**Comment by SHUMKASHUN** [comment]
Hi,
chainyo/alpaca-lora-7b is a 8bit model which reduce the memory consumption. However, gpt-neo2.7B should be able to fit in 11G RTX 2080 Ti. Could you please check it there any other programs are using the GPU?

**Comment by lyb19930105** [comment]
> Hi, chainyo/alpaca-lora-7b is a 8bit model which reduce the memory consumption. However, gpt-neo2.7B should be able to fit in 11G RTX 2080 Ti. Could you please check it there any other programs are using the GPU?

![image](https://user-images.githubusercontent.com/19767917/230316734-bec72cb6-f763-4b16-9722-067ea076e021.png)
This is the GPU status before I ran the program

**Comment by shizhediao** [comment]
Hi,

It seems ok with the GPU status. 
Was this issue resolved later on?

**Comment by shizhediao** [comment]
This issue has been marked as stale because it has not had recent activity. If you think this still needs to be addressed please feel free to reopen this issue. Thanks
