### ISSUE TITLE
Run examples/chatbot.py ERROR

### ISSUE THREAD

**Issue by Ainierheokami** [OptimalScale/LMFlow#154]
I created a lmflow docker in win11 wsl2.

When I run this command, 

```python examples/chatbot.py --model_name_or_path models/llama-7b-hf --deepspeed configs/ds_config_chatbot.json```

I get an error：

```
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 33/33 [01:01<00:00,  1.86s/it]
Traceback (most recent call last):
  File "/LMFlow/examples/chatbot.py", line 117, in <module>
    main()
  File "/LMFlow/examples/chatbot.py", line 44, in main
    model = AutoModel.get_model(
  File "/LMFlow/src/lmflow/models/auto_model.py", line 14, in get_model
    return HFDecoderModel(model_args, *args, **kwargs)
  File "/LMFlow/src/lmflow/models/hf_decoder_model.py", line 224, in __init__
    self.ds_engine = deepspeed.initialize(model=self.backend_model, config_params=ds_config)[0]
  File "/venv/lib/python3.9/site-packages/deepspeed/__init__.py", line 125, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/venv/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 297, in __init__
    self._configure_distributed_model(model)
  File "/venv/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1146, in _configure_distributed_model
    self.module.to(self.device)
  File "/venv/lib/python3.9/site-packages/transformers/modeling_utils.py", line 1861, in to
    return super().to(*args, **kwargs)
  File "/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!
```

Is this a problem with my model?

**Comment by research4pan** [comment]
Thanks for your interest in LMFlow! This issue has been reported several times before and it turns out to be caused by RAM-optimized loading. To turn off RAM-optimized loading, you may directly set `--use_ram_optimized_load False`.

This issue is also fixed in our latest main branch via [this pull request](https://github.com/OptimalScale/LMFlow/pull/148). You may update the code to see if the issue still exists.

Thanks 😄

**Comment by Ainierheokami** [comment]
> Thanks for your interest in LMFlow! This issue has been reported several times before and it turns out to be caused by RAM-optimized loading. To turn off RAM-optimized loading, you may directly set `--use_ram_optimized_load False`.
> 
> This issue is also fixed in our latest main branch via [this pull request](https://github.com/OptimalScale/LMFlow/pull/148). You may update the code to see if the issue still exists.
> 
> Thanks 😄

Thanks for your help, it worked!
