### ISSUE TITLE
运行evaluation.sh时报错，显示LLaMATokenizer does not exist

### ISSUE THREAD

**Issue by qooobe** [OptimalScale/LMFlow#161]
使用llama模型时产生如下错误，
Traceback (most recent call last):
  File "/data/hq/LMFlow/./examples/evaluate.py", line 34, in <module>
    model = AutoModel.get_model(model_args, tune_strategy='none', ds_config=ds_config)
  File "/data/hq/LMFlow/src/lmflow/models/auto_model.py", line 14, in get_model
    return HFDecoderModel(model_args, *args, **kwargs)
  File "/data/hq/LMFlow/src/lmflow/models/hf_decoder_model.py", line 224, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(model_args.model_name_or_path)
  File "/root/miniconda3/envs/lmflow/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 691, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class LLaMATokenizer does not exist or is not currently imported.
[2023-04-07 18:00:05,022] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 3428
[2023-04-07 18:00:05,023] [ERROR] [launch.py:324:sigkill_handler] ['/root/miniconda3/envs/lmflow/bin/python', '-u', './examples/evaluate.py', '--local_rank=0', '--answer_type', 'text', '--model_name_or_path', './output_models/llama-7b-hf', '--lora_model_path', './output_models/llama7b-lora-380k', '--dataset_path', './data/alpaca/test', '--prompt_structure', 'Input: {input}', '--deepspeed', './examples/ds_config.json', '--use_ram_optimized_load', 'False'] exits with return code = 1

请问这个问题该如何解决？

**Comment by research4pan** [comment]
Thanks for your interest in LMFlow! This is highly possible to be caused by the dependency problem of `transformers`. You may install the dependency according to the [setup section](https://github.com/OptimalScale/LMFlow/blob/main/README.md#1setup) and that should fix the issue. Thanks 😄

**Comment by lyb19930105** [comment]
遇到相同的问题。requirements.txt里面的transformers包地址https://github.com/huggingface/transformers@c612628045822f909020f7eb6784c79700813eda已经失效。
另外，从https://github.com/huggingface/transformers下载源码安装后，仍然报相同的问题

**Comment by lyb19930105** [comment]
这个是历史原因，以前叫LLaMATokenizer 现在叫LlamaTokenizer，有个解决办法是从 https://github.com/huggingface/transformers 下载源码后，修改src/transformers/models/auto/tokenization_auto.py，在1068行后面加上2行代码：
![image](https://user-images.githubusercontent.com/19767917/235347115-4ede7ff7-ae3d-49b9-b86c-e327aa83943c.png)
然后再回到主目录执行pip3 install -e .
