### ISSUE TITLE
运行./scripts/run_finetune_with_lora.sh指令错误

### ISSUE THREAD

**Issue by LiuMingwu** [OptimalScale/LMFlow#162]
wandb: ERROR api_key not configured (no-tty). call wandb.login(key=[your_api_key])
Traceback (most recent call last):
  File "/home/lmw22/LMFlow/examples/finetune.py", line 70, in <module>
    main()
  File "/home/lmw22/LMFlow/examples/finetune.py", line 66, in main
    tuned_model = finetuner.tune(model=model, lm_dataset=lm_dataset)
  File "/home/lmw22/LMFlow/src/lmflow/pipeline/finetuner.py", line 232, in tune
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/lmw22/.conda/envs/lmflow/lib/python3.9/site-packages/transformers/trainer.py", line 1639, in train
    return inner_training_loop(
  File "/home/lmw22/.conda/envs/lmflow/lib/python3.9/site-packages/transformers/trainer.py", line 1822, in _inner_training_loop
    self.control = self.callback_handler.on_train_begin(args, self.state, self.control)
  File "/home/lmw22/.conda/envs/lmflow/lib/python3.9/site-packages/transformers/trainer_callback.py", line 353, in on_train_begin
    return self.call_event("on_train_begin", args, state, control)
  File "/home/lmw22/.conda/envs/lmflow/lib/python3.9/site-packages/transformers/trainer_callback.py", line 397, in call_event
    result = getattr(callback, event)(
  File "/home/lmw22/.conda/envs/lmflow/lib/python3.9/site-packages/transformers/integrations.py", line 764, in on_train_begin
    self.setup(args, state, model, **kwargs)
  File "/home/lmw22/.conda/envs/lmflow/lib/python3.9/site-packages/transformers/integrations.py", line 738, in setup
    self._wandb.init(
  File "/home/lmw22/.conda/envs/lmflow/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1140, in init
    wi.setup(kwargs)
  File "/home/lmw22/.conda/envs/lmflow/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 288, in setup
    wandb_login._login(
  File "/home/lmw22/.conda/envs/lmflow/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 298, in _login
    wlogin.prompt_api_key()
  File "/home/lmw22/.conda/envs/lmflow/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 228, in prompt_api_key
    raise UsageError("api_key not configured (no-tty). call " + directive)
wandb.errors.UsageError: api_key not configured (no-tty). call wandb.login(key=[your_api_key])
[2023-04-07 17:31:10,115] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 14145
[2023-04-07 17:31:10,116] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 14146

**Comment by research4pan** [comment]
Thanks for your attention! Looks like `wandb` is not initialized. You may use `wandb login` to enable wandb, which requires an account in [wandb.ai](https://wandb.ai/).

Alternatively, you may disable wandb via `export WANDB_MODE=disabled`. Hope that solves your issues. Thanks 😄

**Comment by LiuMingwu** [comment]
Ok,Thanks a lot!
