### ISSUE TITLE
Training Computing Resource Recommendation

### ISSUE THREAD

**Issue by brucewinger** [OptimalScale/LMFlow#167]
If I want to reproduce the training results using Llama-7b and Lora, and fine-tune the model for a specific domain (task tuning), what kind of GPUs should I use? I have attempted to use two 3090Ti GPUs, but I encountered a torch.cuda.OutOfMemoryError: CUDA out of memory. And to avoid out of memory, what DeepSpeed config should I use ? Thanks

**Comment by research4pan** [comment]
Thanks for your interest in LMFlow! Normally a single RTX 3090 (24GB) GPU is sufficient for finetuning Llama-7b and Lora, with `ds_config_zero3.json` config. If you don't have enough RAM, i.e. CPU memory, you may switch to `ds_config_zero2.json` or turn off the offload options in `ds_config_zero3.json`, but larger GPU memory will be required.

Hope that answers your questions. Thanks 😄

**Comment by brucewinger** [comment]
used `ds_config_zero3.json`, got following out of memory error.

`[2023-04-08 19:27:43,013] [WARNING] [runner.py:186:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2023-04-08 19:27:43,027] [INFO] [runner.py:550:main] cmd = /root/miniconda3/envs/lmflow/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMV19 --master_addr=127.0.0.1 --master_port=11000 --enable_each_rank_log=None examples/finetune.py --model_name_or_path ../llama-7b-hf --dataset_path /mnt/disk1/cc/LMFlow/data/example_dataset/train --output_dir /mnt/disk1/cc/LMFlow/output_models/cc_run_0408 --overwrite_output_dir --num_train_epochs 0.01 --learning_rate 1e-4 --block_size 512 --per_device_train_batch_size 1 --use_lora 1 --lora_r 8 --save_aggregated_lora 0 --lora_model_path output_models/llama7b-lora-170k
[2023-04-08 19:27:44,462] [INFO] [launch.py:142:main] WORLD INFO DICT: {'localhost': [0, 1]}
[2023-04-08 19:27:44,462] [INFO] [launch.py:148:main] nnodes=1, num_local_procs=2, node_rank=0
[2023-04-08 19:27:44,462] [INFO] [launch.py:161:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1]})
[2023-04-08 19:27:44,462] [INFO] [launch.py:162:main] dist_world_size=2
[2023-04-08 19:27:44,462] [INFO] [launch.py:164:main] Setting CUDA_VISIBLE_DEVICES=0,1
04/08/2023 19:28:51 - WARNING - lmflow.pipeline.finetuner - Process rank: 0, device: cuda:0, n_gpu: 1distributed training: True, 16-bits training: False
04/08/2023 19:28:51 - WARNING - lmflow.pipeline.finetuner - Process rank: 1, device: cuda:1, n_gpu: 1distributed training: True, 16-bits training: False
Downloading and preparing dataset json/default to /root/.cache/huggingface/datasets/json/default-463b362797b8ecba/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51...
Downloading data files: 100%|██████████| 1/1 [00:00<00:00, 4120.14it/s]
Extracting data files: 100%|██████████| 1/1 [00:00<00:00, 680.56it/s]
Dataset json downloaded and prepared to /root/.cache/huggingface/datasets/json/default-463b362797b8ecba/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51. Subsequent calls will reuse this data.
04/08/2023 19:29:02 - WARNING - datasets.builder - Found cached dataset json (/root/.cache/huggingface/datasets/json/default-463b362797b8ecba/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51)
Loading checkpoint shards: 100%|██████████| 33/33 [00:08<00:00,  3.75it/s]
Loading checkpoint shards:  97%|█████████▋| 32/33 [00:09<00:00,  3.47it/s]trainable params: 4194304 || all params: 6742609920 || trainable%: 0.06220594176090199
Loading checkpoint shards: 100%|██████████| 33/33 [00:09<00:00,  3.53it/s]
trainable params: 4194304 || all params: 6742609920 || trainable%: 0.06220594176090199
Running tokenizer on dataset:   0%|          | 0/50 [00:00<?, ? examples/s][WARNING|tokenization_utils_base.py:2431] 2023-04-08 19:30:23,869 >> Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
04/08/2023 19:30:50 - WARNING - datasets.arrow_dataset - Loading cached processed dataset at /root/.cache/huggingface/datasets/json/default-463b362797b8ecba/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-bdec6107e9a75956.arrow
04/08/2023 19:30:50 - WARNING - datasets.arrow_dataset - Loading cached processed dataset at /root/.cache/huggingface/datasets/json/default-463b362797b8ecba/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-d9c28dbaba212db4.arrow
Traceback (most recent call last):
  File "/mnt/disk1/cc/LMFlow/examples/finetune.py", line 70, in <module>
    main()
  File "/mnt/disk1/cc/LMFlow/examples/finetune.py", line 66, in main
    tuned_model = finetuner.tune(model=model, lm_dataset=lm_dataset)
  File "/mnt/disk1/cc/LMFlow/src/lmflow/pipeline/finetuner.py", line 212, in tune
    trainer = Trainer(
  File "/root/miniconda3/envs/lmflow/lib/python3.9/site-packages/transformers/trainer.py", line 478, in __init__
    self._move_model_to_device(model, args.device)
  File "/root/miniconda3/envs/lmflow/lib/python3.9/site-packages/transformers/trainer.py", line 720, in _move_model_to_device
    model = model.to(device)
  File "/root/miniconda3/envs/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/root/miniconda3/envs/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/root/miniconda3/envs/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/root/miniconda3/envs/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 4 more times]
  File "/root/miniconda3/envs/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/root/miniconda3/envs/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 172.00 MiB (GPU 1; 23.70 GiB total capacity; 22.84 GiB already allocated; 150.56 MiB free; 22.84 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "/mnt/disk1/cc/LMFlow/examples/finetune.py", line 70, in <module>
    main()
  File "/mnt/disk1/cc/LMFlow/examples/finetune.py", line 66, in main
    tuned_model = finetuner.tune(model=model, lm_dataset=lm_dataset)
  File "/mnt/disk1/cc/LMFlow/src/lmflow/pipeline/finetuner.py", line 212, in tune
    trainer = Trainer(
  File "/root/miniconda3/envs/lmflow/lib/python3.9/site-packages/transformers/trainer.py", line 478, in __init__
    self._move_model_to_device(model, args.device)
  File "/root/miniconda3/envs/lmflow/lib/python3.9/site-packages/transformers/trainer.py", line 720, in _move_model_to_device
    model = model.to(device)
  File "/root/miniconda3/envs/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/root/miniconda3/envs/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/root/miniconda3/envs/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/root/miniconda3/envs/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 4 more times]
  File "/root/miniconda3/envs/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/root/miniconda3/envs/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 172.00 MiB (GPU 0; 23.70 GiB total capacity; 22.84 GiB already allocated; 150.56 MiB free; 22.84 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

Any idea on this ?

**Comment by shizhediao** [comment]
This issue has been marked as stale because it has not had recent activity. If you think this still needs to be addressed please feel free to reopen this issue. Thanks
