### ISSUE TITLE
No module named 'torch._six' when running run_finetune_with_lora.sh

### ISSUE THREAD

**Issue by MaiziXiao** [OptimalScale/LMFlow#170]
Got this error running "./scripts/run_finetune_with_lora.sh", seems like a dependency issue, anybody got the same error here?

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1126, in _get_module
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1126, in _get_module
        return importlib.import_module("." + module_name, self.__name__)return importlib.import_module("." + module_name, self.__name__)

  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)    
return _bootstrap._gcd_import(name[level:], package, level)  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/lib/python3.8/site-packages/transformers/trainer.py", line 169, in <module>
  File "/opt/conda/lib/python3.8/site-packages/transformers/trainer.py", line 169, in <module>
    from apex import amp
  File "/opt/conda/lib/python3.8/site-packages/apex/__init__.py", line 8, in <module>
    from apex import amp
  File "/opt/conda/lib/python3.8/site-packages/apex/__init__.py", line 8, in <module>
    from . import amp
  File "/opt/conda/lib/python3.8/site-packages/apex/amp/__init__.py", line 1, in <module>
    from . import amp
  File "/opt/conda/lib/python3.8/site-packages/apex/amp/__init__.py", line 1, in <module>
    from .amp import init, half_function, float_function, promote_function,\
  File "/opt/conda/lib/python3.8/site-packages/apex/amp/amp.py", line 5, in <module>
    from .amp import init, half_function, float_function, promote_function,\
  File "/opt/conda/lib/python3.8/site-packages/apex/amp/amp.py", line 5, in <module>
    from .frontend import *
  File "/opt/conda/lib/python3.8/site-packages/apex/amp/frontend.py", line 2, in <module>
    from .frontend import *
  File "/opt/conda/lib/python3.8/site-packages/apex/amp/frontend.py", line 2, in <module>
    from ._initialize import _initialize
  File "/opt/conda/lib/python3.8/site-packages/apex/amp/_initialize.py", line 2, in <module>
    from ._initialize import _initialize
  File "/opt/conda/lib/python3.8/site-packages/apex/amp/_initialize.py", line 2, in <module>
    from torch._six import string_classes
ModuleNotFoundError: No module named 'torch._six'

The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
from torch._six import string_classes  File "examples/finetune.py", line 29, in <module>

ModuleNotFoundError: No module named 'torch._six'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "examples/finetune.py", line 29, in <module>
    from lmflow.pipeline.auto_pipeline import AutoPipeline
  File "/ossfs/workspace/LMFlow/src/lmflow/pipeline/auto_pipeline.py", line 6, in <module>
    from lmflow.pipeline.auto_pipeline import AutoPipeline
  File "/ossfs/workspace/LMFlow/src/lmflow/pipeline/auto_pipeline.py", line 6, in <module>
    from lmflow.pipeline.finetuner import Finetuner    
from lmflow.pipeline.finetuner import Finetuner
  File "/ossfs/workspace/LMFlow/src/lmflow/pipeline/finetuner.py", line 14, in <module>
  File "/ossfs/workspace/LMFlow/src/lmflow/pipeline/finetuner.py", line 14, in <module>
        from transformers import (from transformers import (

  File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1116, in __getattr__
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1116, in __getattr__
        module = self._get_module(self._class_to_module[name])module = self._get_module(self._class_to_module[name])

  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1128, in _get_module
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1128, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.trainer because of the following error (look up to see its traceback):
No module named 'torch._six'
    raise RuntimeError(
RuntimeError: Failed to import transformers.trainer because of the following error (look up to see its traceback):
No module named 'torch._six'
[2023-04-08 15:29:09,580] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 4648
[2023-04-08 15:29:09,583] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 4649
[2023-04-08 15:29:09,583] [ERROR] [launch.py:324:sigkill_handler] ['/opt/conda/bin/python', '-u', 'examples/finetune.py', '--local_rank=1', '--model_name_or_path', 'facebook/galactica-1.3b', '--dataset_path', '/ossfs/workspace/LMFlow/data/alpaca/train', '--output_dir', '/ossfs/workspace/LMFlow/output_models/finetune_with_lora', '--overwrite_output_dir', '--num_train_epochs', '0.01', '--learning_rate', '1e-4', '--block_size', '512', '--per_device_train_batch_size', '1', '--use_lora', '1', '--lora_r', '8', '--save_aggregated_lora', '0', '--deepspeed', 'configs/ds_config_zero2.json', '--bf16', '--run_name', 'finetune_with_lora', '--validation_split_percentage', '0', '--logging_steps', '20', '--do_train', '--ddp_timeout', '72000', '--save_steps', '5000', '--dataloader_num_workers', '1'] exits with return code = 1

**Comment by research4pan** [comment]
Thanks for your attention! It looks like a dependency problem. Could you provide the installed packages list via `pip list` so we may check that for you? Thanks 😄

**Comment by MaiziXiao** [comment]
I have downgraded my torch version from 2.0 to 1.13.1 and the issue was gone
