### ISSUE TITLE
windows没法装deepspeed吧 ，有人验证过没？

### ISSUE THREAD

**Issue by doseralutajy** [OptimalScale/LMFlow#173]
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting deepspeed==0.8.3
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/0f/c0/9b57e9ec56f6f405726a384b109f8da1267e41feea081850c2fce1735712/deepspeed-0.8.3.tar.gz (765 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7'
      test.c
      LINK : fatal error LNK1181: 无法打开输入文件“aio.lib”
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\1\AppData\Local\Temp\pip-install-yqlqsg3j\deepspeed_43959dd1e4284318a6a8bc41546a4984\setup.py", line 156, in <module>
          abort(f"Unable to pre-compile {op_name}")
        File "C:\Users\1\AppData\Local\Temp\pip-install-yqlqsg3j\deepspeed_43959dd1e4284318a6a8bc41546a4984\setup.py", line 48, in abort
          assert False, msg
      AssertionError: Unable to pre-compile async_io
      [WARNING] Torch did not find cuda available, if cross-compiling or running with cpu only you can ignore this message. Adding compute capability for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2)
      DS_BUILD_OPS=1
       [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
       [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
       [WARNING]  One can disable async_io with DS_BUILD_AIO=0
       [ERROR]  Unable to pre-compile async_io
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by 2003pro** [comment]
Thanks for the attention on LMFlow. Our support for Windows/Mac OSX is still testing and not fully prepared yet. 

As a first step, we recommend you use Linux servers, Linux virtual machines, [Docker](https://github.com/OptimalScale/LMFlow/tree/main/docker) or [Google Colab](https://colab.research.google.com/) to run experiments, which provides free T4 GPUs and V100/A100 if you have Google Pro/Pro+ account. 

我们对Windows以及Mac OSX的支持仍在开发测试中，建议大家先使用Linux服务器、Linux虚拟机、[Docker](https://github.com/OptimalScale/LMFlow/tree/main/docker)或者[Google Colab](https://colab.research.google.com/)来进行实验，Google Colab上有免费的T4 (16GB显存）GPU，以及收费的V100（16GB显存）和A100（40GB显存）GPU（需要Google Pro/Pro+用户）🙏

**Comment by doseralutajy** [comment]
Thank you, please ask this recommended configuration and the minimum configuration of what graphics cards are required

> Thanks for the attention on LMFlow. Our support for Windows/Mac OSX is still testing and not fully prepared yet.
> 
> As a first step, we recommend you use Linux servers, Linux virtual machines, [Docker](https://github.com/OptimalScale/LMFlow/tree/main/docker) or [Google Colab](https://colab.research.google.com/) to run experiments, which provides free T4 GPUs and V100/A100 if you have Google Pro/Pro+ account.
> 
> 我们对Windows以及Mac OSX的支持仍在开发测试中，建议大家先使用Linux服务器、Linux虚拟机、[Docker](https://github.com/OptimalScale/LMFlow/tree/main/docker)或者[Google Colab](https://colab.research.google.com/)来进行实验，Google Colab上有免费的T4 (16GB显存）GPU，以及收费的V100（16GB显存）和A100（40GB显存）GPU（需要Google Pro/Pro+用户）🙏

**Comment by research4pan** [comment]
> Thank you, please ask this recommended configuration and the minimum configuration of what graphics cards are required
> 
> > Thanks for the attention on LMFlow. Our support for Windows/Mac OSX is still testing and not fully prepared yet.
> > As a first step, we recommend you use Linux servers, Linux virtual machines, [Docker](https://github.com/OptimalScale/LMFlow/tree/main/docker) or [Google Colab](https://colab.research.google.com/) to run experiments, which provides free T4 GPUs and V100/A100 if you have Google Pro/Pro+ account.
> > 我们对Windows以及Mac OSX的支持仍在开发测试中，建议大家先使用Linux服务器、Linux虚拟机、[Docker](https://github.com/OptimalScale/LMFlow/tree/main/docker)或者[Google Colab](https://colab.research.google.com/)来进行实验，Google Colab上有免费的T4 (16GB显存）GPU，以及收费的V100（16GB显存）和A100（40GB显存）GPU（需要Google Pro/Pro+用户）🙏

Thanks! The configuration may vary if you use different models. According to our experience, finetuning a 7b models can be done in a RTX 3090 (24GB) GPU card. For larger models, you may need quantization or larger GPU memory. Hope that answers your question. Thanks 😄

**Comment by shizhediao** [comment]
This issue has been marked as stale because it has not had recent activity. If you think this still needs to be addressed please feel free to reopen this issue. Thanks!

**Comment by NingBoHao** [comment]
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7'
在window10 安装 python 环境中安装 
conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
详情见https://pytorch.org/get-started/locally/
