### ISSUE TITLE
Error when changing the script to fine tune a Llama based model

### ISSUE THREAD

**Issue by MaiziXiao** [OptimalScale/LMFlow#181]
torch version: 1.13.1+cu116
cudnn version: 8302

I managed to run finetune scripts with "galactica-1.3b" model. After that I tried to modify the scripts ./scripts/run_finetune_with_lora.sh to work with the Llama model from huggingface ("decapoda-research/llama-7b-hf").

At first I tried with 2 GPUs (P100s) got the error log 
`$./scripts/run_finetune_with_lora_llama.sh
[2023-04-09 15:00:43,896] [WARNING] [runner.py:186:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2023-04-09 15:00:43,909] [INFO] [runner.py:550:main] cmd = /opt/conda/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMV19 --master_addr=127.0.0.1 --master_port=11000 --enable_each_rank_log=None examples/finetune.py --model_name_or_path /ossfs/workspace/LLMs/llama-7b-hf --dataset_path /ossfs/workspace/LMFlow/data/alpaca/train --output_dir /ossfs/workspace/LMFlow/output_models/finetune_with_lora_llama --overwrite_output_dir --num_train_epochs 0.01 --learning_rate 1e-4 --block_size 512 --per_device_train_batch_size 1 --use_lora 1 --lora_r 8 --save_aggregated_lora 0 --deepspeed configs/ds_config_zero2.json --fp16 --run_name finetune_with_lora --validation_split_percentage 0 --logging_steps 20 --do_train --ddp_timeout 72000 --save_steps 5000 --dataloader_num_workers 1
[2023-04-09 15:00:46,896] [INFO] [launch.py:135:main] 0 USE_NCCL=1
[2023-04-09 15:00:46,896] [INFO] [launch.py:142:main] WORLD INFO DICT: {'localhost': [0, 1]}
[2023-04-09 15:00:46,896] [INFO] [launch.py:148:main] nnodes=1, num_local_procs=2, node_rank=0
[2023-04-09 15:00:46,896] [INFO] [launch.py:161:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1]})
[2023-04-09 15:00:46,896] [INFO] [launch.py:162:main] dist_world_size=2
[2023-04-09 15:00:46,897] [INFO] [launch.py:164:main] Setting CUDA_VISIBLE_DEVICES=0,1
[2023-04-09 15:00:53,546] [INFO] [comm.py:652:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[W socket.cpp:426] [c10d] The server socket cannot be initialized on [::]:11000 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [localhost]:11000 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [localhost]:11000 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [localhost]:11000 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [localhost]:11000 (errno: 97 - Address family not supported by protocol).
04/09/2023 15:00:54 - WARNING - lmflow.pipeline.finetuner - Process rank: 0, device: cuda:0, n_gpu: 1distributed training: True, 16-bits training: True
04/09/2023 15:00:55 - WARNING - lmflow.pipeline.finetuner - Process rank: 1, device: cuda:1, n_gpu: 1distributed training: True, 16-bits training: True
04/09/2023 15:00:57 - WARNING - datasets.builder - Found cached dataset json (/root/.cache/huggingface/datasets/json/default-4aca9bae2e6de0a9/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51)
04/09/2023 15:00:57 - WARNING - datasets.builder - Found cached dataset json (/root/.cache/huggingface/datasets/json/default-4aca9bae2e6de0a9/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51)
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 33/33 [03:26<00:00,  6.25s/it]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 33/33 [03:20<00:00,  6.07s/it]
trainable params: 4194304 || all params: 6742609920 || trainable%: 0.06220594176090199
trainable params: 4194304 || all params: 6742609920 || trainable%: 0.06220594176090199
Traceback (most recent call last):
  File "examples/finetune.py", line 70, in <module>
    main()
  File "examples/finetune.py", line 58, in main
    with pipeline_args.main_process_first(desc="dataset map tokenization"):
  File "/opt/conda/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/opt/conda/lib/python3.8/site-packages/transformers/training_args.py", line 1877, in main_process_first
    torch.distributed.barrier()
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 3145, in barrier
    work = default_pg.barrier(opts=opts)
RuntimeError: [1] is setting up NCCL communicator and retreiving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: Connection reset by peer
[2023-04-09 15:11:02,586] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 12399
[2023-04-09 15:11:02,586] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 12400
[2023-04-09 15:11:04,337] [ERROR] [launch.py:324:sigkill_handler] ['/opt/conda/bin/python', '-u', 'examples/finetune.py', '--local_rank=1', '--model_name_or_path', '/ossfs/workspace/LLMs/llama-7b-hf', '--dataset_path', '/ossfs/workspace/LMFlow/data/alpaca/train', '--output_dir', '/ossfs/workspace/LMFlow/output_models/finetune_with_lora_llama', '--overwrite_output_dir', '--num_train_epochs', '0.01', '--learning_rate', '1e-4', '--block_size', '512', '--per_device_train_batch_size', '1', '--use_lora', '1', '--lora_r', '8', '--save_aggregated_lora', '0', '--deepspeed', 'configs/ds_config_zero2.json', '--fp16', '--run_name', 'finetune_with_lora', '--validation_split_percentage', '0', '--logging_steps', '20', '--do_train', '--ddp_timeout', '72000', '--save_steps', '5000', '--dataloader_num_workers', '1'] exits with return code = -9`

It looks to me like an issue related to distributed training, so afterwards I set the deepspeed parameter "--num_gpus=1", But I still got another error which is not very clear to me
`$./scripts/run_finetune_with_lora_llama.sh "--num_gpus=1 --master_port 10001"
[2023-04-09 15:54:56,299] [WARNING] [runner.py:186:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2023-04-09 15:54:56,313] [INFO] [runner.py:550:main] cmd = /opt/conda/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=10001 --enable_each_rank_log=None examples/finetune.py --model_name_or_path /ossfs/workspace/LLMs/llama-7b-hf --dataset_path /ossfs/workspace/LMFlow/data/alpaca/train --output_dir /ossfs/workspace/LMFlow/output_models/finetune_with_lora_llama --overwrite_output_dir --num_train_epochs 0.01 --learning_rate 1e-4 --block_size 512 --per_device_train_batch_size 1 --use_lora 1 --lora_r 8 --save_aggregated_lora 0 --deepspeed configs/ds_config_zero2.json --fp16 --run_name finetune_with_lora --validation_split_percentage 0 --logging_steps 20 --do_train --ddp_timeout 72000 --save_steps 5000 --dataloader_num_workers 1
[2023-04-09 15:54:59,241] [INFO] [launch.py:135:main] 0 USE_NCCL=1
[2023-04-09 15:54:59,241] [INFO] [launch.py:142:main] WORLD INFO DICT: {'localhost': [0]}
[2023-04-09 15:54:59,241] [INFO] [launch.py:148:main] nnodes=1, num_local_procs=1, node_rank=0
[2023-04-09 15:54:59,242] [INFO] [launch.py:161:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2023-04-09 15:54:59,242] [INFO] [launch.py:162:main] dist_world_size=1
[2023-04-09 15:54:59,242] [INFO] [launch.py:164:main] Setting CUDA_VISIBLE_DEVICES=0
[2023-04-09 15:55:05,427] [INFO] [comm.py:652:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[W socket.cpp:426] [c10d] The server socket cannot be initialized on [::]:10001 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [localhost]:10001 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [localhost]:10001 (errno: 97 - Address family not supported by protocol).
04/09/2023 15:55:05 - WARNING - lmflow.pipeline.finetuner - Process rank: 0, device: cuda:0, n_gpu: 1distributed training: True, 16-bits training: True
04/09/2023 15:55:07 - WARNING - datasets.builder - Found cached dataset json (/root/.cache/huggingface/datasets/json/default-4aca9bae2e6de0a9/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51)
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 33/33 [03:06<00:00,  5.64s/it]
trainable params: 4194304 || all params: 6742609920 || trainable%: 0.06220594176090199
[2023-04-09 16:05:08,889] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 33265
[2023-04-09 16:05:08,890] [ERROR] [launch.py:324:sigkill_handler] ['/opt/conda/bin/python', '-u', 'examples/finetune.py', '--local_rank=0', '--model_name_or_path', '/ossfs/workspace/LLMs/llama-7b-hf', '--dataset_path', '/ossfs/workspace/LMFlow/data/alpaca/train', '--output_dir', '/ossfs/workspace/LMFlow/output_models/finetune_with_lora_llama', '--overwrite_output_dir', '--num_train_epochs', '0.01', '--learning_rate', '1e-4', '--block_size', '512', '--per_device_train_batch_size', '1', '--use_lora', '1', '--lora_r', '8', '--save_aggregated_lora', '0', '--deepspeed', 'configs/ds_config_zero2.json', '--fp16', '--run_name', 'finetune_with_lora', '--validation_split_percentage', '0', '--logging_steps', '20', '--do_train', '--ddp_timeout', '72000', '--save_steps', '5000', '--dataloader_num_workers', '1'] exits with return code = -9`

Any idea what is going on here?

**Comment by research4pan** [comment]
Thanks for your interest in LMFlow! Looks like the port is not good. 
```
...
The server socket cannot be initialized on [::]:10001 (errno: 97 - Address family not supported by protocol). 
...
```
You may change `--master_port=11000` in `run_finetune_with_lora_llama.sh` to other ports, or simply remove it (which will use the default port 29500). The detailed error messages goes to `log/finetune_with_lora/train.err`, you can also check that file for more information. Also, it would be nice if you could provide your environment settings, such as NCCL version, CUDA version, CUDA driver version, etc. so we may check that for you. Thanks 😄

**Comment by MaiziXiao** [comment]
My torch and cuda version is as following:
```
--------------------------------------------------
DeepSpeed C++/CUDA extension op report
--------------------------------------------------
NOTE: Ops not installed will be just-in-time (JIT) compiled at
      runtime if needed. Op compatibility means that your system
      meet the required dependencies to JIT install the op.
--------------------------------------------------
JIT compiled ops requires ninja
ninja .................. [OKAY]
--------------------------------------------------
op name ................ installed .. compatible
--------------------------------------------------
async_io ............... [NO] ....... [OKAY]
cpu_adagrad ............ [NO] ....... [OKAY]
cpu_adam ............... [NO] ....... [OKAY]
fused_adam ............. [NO] ....... [OKAY]
fused_lamb ............. [NO] ....... [OKAY]
quantizer .............. [NO] ....... [OKAY]
random_ltd ............. [NO] ....... [OKAY]
 [WARNING]  please install triton==1.0.0 if you want to use sparse attention
sparse_attn ............ [NO] ....... [NO]
spatial_inference ...... [NO] ....... [OKAY]
transformer ............ [NO] ....... [OKAY]
stochastic_transformer . [NO] ....... [OKAY]
transformer_inference .. [NO] ....... [OKAY]
utils .................. [NO] ....... [OKAY]
--------------------------------------------------
DeepSpeed general environment info:
torch install path ............... ['/opt/conda/lib/python3.8/site-packages/torch']
torch version .................... 1.13.1+cu116
deepspeed install path ........... ['/opt/conda/lib/python3.8/site-packages/deepspeed']
deepspeed info ................... 0.8.3, unknown, unknown
torch cuda version ............... 11.6
torch hip version ................ None
nvcc version ..................... 11.6
deepspeed wheel compiled w. ...... torch 1.13, cuda 11.6
```
I have managed to run training on "galactica-1.3b" but stilled failed to run Llama after I tried the default port. I don't get any message from  ```log/finetune_with_lora/train.err```. It looks to me that it is an issue related to deepspeed but not sure how to resolve it.
```
$./scripts/run_finetune_with_lora_llama.sh
[2023-04-10 13:28:48,546] [WARNING] [runner.py:186:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2023-04-10 13:28:48,932] [INFO] [runner.py:550:main] cmd = /opt/conda/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMV19 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None examples/finetune.py --model_name_or_path /ossfs/workspace/LLMs/llama-7b-hf --dataset_path /ossfs/workspace/LMFlow/data/alpaca/train --output_dir /ossfs/workspace/LMFlow/output_models/finetune_with_lora_llama --overwrite_output_dir --num_train_epochs 0.01 --learning_rate 1e-4 --block_size 512 --per_device_train_batch_size 1 --use_lora 1 --lora_r 8 --save_aggregated_lora 0 --deepspeed configs/ds_config_zero2.json --bf16 --run_name finetune_with_lora --validation_split_percentage 0 --logging_steps 20 --do_train --ddp_timeout 72000 --save_steps 5000 --dataloader_num_workers 1
[2023-04-10 13:28:50,947] [INFO] [launch.py:135:main] 0 USE_NCCL=1
[2023-04-10 13:28:50,947] [INFO] [launch.py:142:main] WORLD INFO DICT: {'localhost': [0, 1]}
[2023-04-10 13:28:50,947] [INFO] [launch.py:148:main] nnodes=1, num_local_procs=2, node_rank=0
[2023-04-10 13:28:50,947] [INFO] [launch.py:161:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1]})
[2023-04-10 13:28:50,947] [INFO] [launch.py:162:main] dist_world_size=2
[2023-04-10 13:28:50,947] [INFO] [launch.py:164:main] Setting CUDA_VISIBLE_DEVICES=0,1
[2023-04-10 13:28:59,010] [INFO] [comm.py:652:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
04/10/2023 13:28:59 - WARNING - lmflow.pipeline.finetuner - Process rank: 1, device: cuda:1, n_gpu: 1distributed training: True, 16-bits training: False
04/10/2023 13:28:59 - WARNING - lmflow.pipeline.finetuner - Process rank: 0, device: cuda:0, n_gpu: 1distributed training: True, 16-bits training: False
Downloading and preparing dataset json/default to /root/.cache/huggingface/datasets/json/default-4aca9bae2e6de0a9/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51...
Downloading data files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 8848.74it/s]
Extracting data files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  4.20it/s]
Dataset json downloaded and prepared to /root/.cache/huggingface/datasets/json/default-4aca9bae2e6de0a9/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51. Subsequent calls will reuse this data.
04/10/2023 13:29:01 - WARNING - datasets.builder - Found cached dataset json (/root/.cache/huggingface/datasets/json/default-4aca9bae2e6de0a9/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51)
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 33/33 [05:11<00:00,  9.43s/it]
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 33/33 [05:15<00:00,  9.56s/it]
trainable params: 4194304 || all params: 6742609920 || trainable%: 0.06220594176090199
trainable params: 4194304 || all params: 6742609920 || trainable%: 0.06220594176090199
[2023-04-10 13:37:41,037] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 9289
[2023-04-10 13:37:41,040] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 9290
[2023-04-10 13:37:41,299] [ERROR] [launch.py:324:sigkill_handler] ['/opt/conda/bin/python', '-u', 'examples/finetune.py', '--local_rank=1', '--model_name_or_path', '/ossfs/workspace/LLMs/llama-7b-hf', '--dataset_path', '/ossfs/workspace/LMFlow/data/alpaca/train', '--output_dir', '/ossfs/workspace/LMFlow/output_models/finetune_with_lora_llama', '--overwrite_output_dir', '--num_train_epochs', '0.01', '--learning_rate', '1e-4', '--block_size', '512', '--per_device_train_batch_size', '1', '--use_lora', '1', '--lora_r', '8', '--save_aggregated_lora', '0', '--deepspeed', 'configs/ds_config_zero2.json', '--bf16', '--run_name', 'finetune_with_lora', '--validation_split_percentage', '0', '--logging_steps', '20', '--do_train', '--ddp_timeout', '72000', '--save_steps', '5000', '--dataloader_num_workers', '1'] exits with return code = -9
```
![image](https://user-images.githubusercontent.com/24979986/230824153-c0ac494a-7d7d-450f-a1f6-07d83df03762.png)




> Thanks for your interest in LMFlow! Looks like the port is not good.
> 
> ```
> ...
> The server socket cannot be initialized on [::]:10001 (errno: 97 - Address family not supported by protocol). 
> ...
> ```
> 
> You may change `--master_port=11000` in `run_finetune_with_lora_llama.sh` to other ports, or simply remove it (which will use the default port 29500). The detailed error messages goes to `log/finetune_with_lora/train.err`, you can also check that file for more information. Also, it would be nice if you could provide your environment settings, such as NCCL version, CUDA version, CUDA driver version, etc. so we can check that for you. Thanks 😄

**Comment by research4pan** [comment]
Hi! Looks like this error is related to the used llama model. I know that `decapoda-research/llama-7b-hf` is not supported in later `transformers` versions. Could you please try `pinkmanlove/llama-7b-hf` to see if the error will occur again? Thanks 😄

**Comment by xiaowan-071** [comment]
I had the same error, I fine-tuned the model on two servers, one of which was normal and the other had a problem, but I have not been able to find out the cause of the problem.

**Comment by research4pan** [comment]
> I had the same error, I fine-tuned the model on two servers, one of which was normal and the other had a problem, but I have not been able to find out the cause of the problem.

This may be caused by dependency or hardware setting problems. You may check if there is any difference between two servers.  Hope that helps 🙏

**Comment by shizhediao** [comment]
This issue has been marked as stale because it has not had recent activity. If you think this still needs to be addressed please feel free to reopen this issue. Thanks
