### ISSUE TITLE
[ERROR] TCPStore ：RuntimeError: Connection reset by peer when I run ./scripts/run_finetune_with_lora.sh with llama-7b-hf

### ISSUE THREAD

**Issue by cxhgh** [OptimalScale/LMFlow#182]
[2023-04-09 16:14:08,583] [WARNING] [runner.py:186:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
Detected CUDA_VISIBLE_DEVICES=0: setting --include=localhost:0
[2023-04-09 16:14:08,597] [INFO] [runner.py:550:main] cmd = /data/backup/LMFlow/lmflow_venv/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=11000 --enable_each_rank_log=None examples/finetune.py --model_name_or_path /data/backup/llama_checkpoint/7B --dataset_path /data/backup/LMFlow/data/alpaca/train --output_dir /data/backup/LMFlow/output_models/finetune_with_lora --overwrite_output_dir --num_train_epochs 0.01 --learning_rate 1e-4 --block_size 512 --per_device_train_batch_size 1 --use_lora 1 --lora_r 8 --deepspeed configs/ds_config_zero3.json --bf16 --run_name finetune_with_lora --validation_split_percentage 0 --logging_steps 20 --do_train --ddp_timeout 72000 --save_steps 5000 --dataloader_num_workers 1
[2023-04-09 16:14:10,472] [INFO] [launch.py:142:main] WORLD INFO DICT: {'localhost': [0]}
[2023-04-09 16:14:10,472] [INFO] [launch.py:148:main] nnodes=1, num_local_procs=1, node_rank=0
[2023-04-09 16:14:10,472] [INFO] [launch.py:161:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2023-04-09 16:14:10,472] [INFO] [launch.py:162:main] dist_world_size=1
[2023-04-09 16:14:10,472] [INFO] [launch.py:164:main] Setting CUDA_VISIBLE_DEVICES=0
[2023-04-09 16:14:13,826] [INFO] [comm.py:652:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
Traceback (most recent call last):
  File "examples/finetune.py", line 70, in <module>
    main()
  File "examples/finetune.py", line 43, in main
    model_args, data_args, pipeline_args = parser.parse_args_into_dataclasses()
  File "/data/backup/LMFlow/lmflow_venv/lib/python3.8/site-packages/transformers/hf_argparser.py", line 332, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 109, in __init__
  File "/data/backup/LMFlow/lmflow_venv/lib/python3.8/site-packages/transformers/training_args.py", line 1227, in __post_init__
    and (self.device.type != "cuda")
  File "/data/backup/LMFlow/lmflow_venv/lib/python3.8/site-packages/transformers/training_args.py", line 1662, in device
    return self._setup_devices
  File "/data/backup/LMFlow/lmflow_venv/lib/python3.8/site-packages/transformers/utils/generic.py", line 54, in __get__
    cached = self.fget(obj)
  File "/data/backup/LMFlow/lmflow_venv/lib/python3.8/site-packages/transformers/training_args.py", line 1594, in _setup_devices
    deepspeed.init_distributed(timeout=timedelta(seconds=self.ddp_timeout))
  File "/data/backup/LMFlow/lmflow_venv/lib/python3.8/site-packages/deepspeed/comm/comm.py", line 656, in init_distributed
    cdb = TorchBackend(dist_backend, timeout, init_method, rank, world_size)
  File "/data/backup/LMFlow/lmflow_venv/lib/python3.8/site-packages/deepspeed/comm/torch.py", line 36, in __init__
    self.init_process_group(backend, timeout, init_method, rank, world_size)
  File "/data/backup/LMFlow/lmflow_venv/lib/python3.8/site-packages/deepspeed/comm/torch.py", line 40, in init_process_group
    torch.distributed.init_process_group(backend,
  File "/data/backup/LMFlow/lmflow_venv/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 888, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/data/backup/LMFlow/lmflow_venv/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 245, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
  File "/data/backup/LMFlow/lmflow_venv/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 176, in _create_c10d_store
    return TCPStore(
RuntimeError: Connection reset by peer
[2023-04-09 16:14:15,490] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 2899724
[2023-04-09 16:14:15,491] [ERROR] [launch.py:324:sigkill_handler] ['/data/backup/LMFlow/lmflow_venv/bin/python', '-u', 'examples/finetune.py', '--local_rank=0', '--model_name_or_path', '/data/backup/llama_checkpoint/7B', '--dataset_path', '/data/backup/LMFlow/data/alpaca/train', '--output_dir', '/data/backup/LMFlow/output_models/finetune_with_lora', '--overwrite_output_dir', '--num_train_epochs', '0.01', '--learning_rate', '1e-4', '--block_size', '512', '--per_device_train_batch_size', '1', '--use_lora', '1', '--lora_r', '8', '--deepspeed', 'configs/ds_config_zero3.json', '--bf16', '--run_name', 'finetune_with_lora', '--validation_split_percentage', '0', '--logging_steps', '20', '--do_train', '--ddp_timeout', '72000', '--save_steps', '5000', '--dataloader_num_workers', '1'] exits with return code = 1

**RuntimeError: Connection reset by peer**
I can not find good method to solve this problem.

**Comment by research4pan** [comment]
Thanks for your interest in LMFlow! Seems like the problem is caused torch distributed TCP problem. Could you please check your torch version `pip show torch`? Thanks 😄

**Comment by shizhediao** [comment]
This issue has been marked as stale because it has not had recent activity. If you think this still needs to be addressed please feel free to reopen this issue. Thanks
