### ISSUE TITLE
No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1'

### ISSUE THREAD

**Issue by Stanford2299** [OptimalScale/LMFlow#185]
(lmflow) PS C:\Users\Satan> pip install deepspeed==0.8.3
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting deepspeed==0.8.3
  Using cached https://mirrors.aliyun.com/pypi/packages/0f/c0/9b57e9ec56f6f405726a384b109f8da1267e41feea081850c2fce1735712/deepspeed-0.8.3.tar.gz (765 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1'
      test.c
      LINK : fatal error LNK1181: 无法打开输入文件“aio.lib”
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Satan\AppData\Local\Temp\pip-install-weoj640z\deepspeed_0beb30a6301e451ca5201ca7abdfc498\setup.py", line 156, in <module>
          abort(f"Unable to pre-compile {op_name}")
        File "C:\Users\Satan\AppData\Local\Temp\pip-install-weoj640z\deepspeed_0beb30a6301e451ca5201ca7abdfc498\setup.py", line 48, in abort
          assert False, msg
      AssertionError: Unable to pre-compile async_io
      [WARNING] Torch did not find cuda available, if cross-compiling or running with cpu only you can ignore this message. Adding compute capability for Pascal, Volta, and Turing (compute capabilities 6.0, 6.1, 6.2)
      DS_BUILD_OPS=1
       [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
       [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
       [WARNING]  One can disable async_io with DS_BUILD_AIO=0
       [ERROR]  Unable to pre-compile async_io
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
(lmflow) PS C:\Users\Satan> pip install aio
>>
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
ERROR: Could not find a version that satisfies the requirement aio (from versions: none)
ERROR: No matching distribution found for aio

**Comment by research4pan** [comment]
Thanks for your interest in LMFlow! Looks like the installation of `deepspeed` is not well-supported in Windows 10, as [an exactly same issues](https://github.com/microsoft/DeepSpeed/issues/1631) have been mentioned under deepspeed's official repository and not resolved yet. We recommend you to try a Linux server/Google Colab/Virtual machine first. We may revisit this issue after the support of deepspeed in Windows 10 is available. Thanks 😄

**Comment by 2003pro** [comment]
You may need to downgrade the deepspeed version to 0.8.2 or 0.8.0. pip install deepspeed==0.8.2.

Also, if this can not work, you can try to switch your pip mirror by modifying /etc/apt/sources.list to other mirror address.

**Comment by NingBoHao** [comment]
安装lmflow 环境中安装deepspeed 出现这个，如何解决

**Comment by shizhediao** [comment]
> You may need to downgrade the deepspeed version to 0.8.2 or 0.8.0. pip install deepspeed==0.8.2.
> 
> Also, if this can not work, you can try to switch your pip mirror by modifying /etc/apt/sources.list to other mirror address.

Please take a look at this. If you still have issues, feel free to put in more information.

Thanks

**Comment by shizhediao** [comment]
This issue has been marked as stale because it has not had recent activity. If you think this still needs to be addressed please feel free to reopen this issue. Thanks
