### ISSUE TITLE
MacBook run "bash scripts/run_finetune.sh ",show "no gpu"

### ISSUE THREAD

**Issue by jinruozai** [OptimalScale/LMFlow#195]
MacBook Pro 2019
os:macos
graphic:AMD Radeon Pro 5500M 8 GB
run:bash scripts/run_finetune.sh   
err:
Traceback (most recent call last):
  File "/Users/jingjiu/miniconda3/bin/deepspeed", line 6, in <module>
[2023-04-10 15:42:17,437] [WARNING] [runner.py:186:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
    main()
  File "/Users/jingjiu/miniconda3/lib/python3.10/site-packages/deepspeed/launcher/runner.py", line 411, in main
    raise RuntimeError("Unable to proceed, no GPU resources available")
RuntimeError: Unable to proceed, no GPU resources available

I should only use cpu to train?any way to use gpu?

**Comment by research4pan** [comment]
Thanks for your interest in LMFlow! The LMFlow codebase is not fully tested in Mac OSX platform. We strongly recommend you to first use a Linux server/Google Colab/Docker to run LMFlow project. If you would like you to use Mac, you may try CPU first. We will let you know once the Mac OSX version passed all tests. Thanks for your understanding 🙏

**Comment by shizhediao** [comment]
This issue has been marked as stale because it has not had recent activity. If you think this still needs to be addressed please feel free to reopen this issue. Thanks
