### ISSUE TITLE
Multi-GPU operation seems to be problematic

### ISSUE THREAD

**Issue by theslugger** [OptimalScale/LMFlow#202]
I can confirm that 29500 is not being used.....

Traceback (most recent call last):
  File "/data1/xxx/chat/LMFlow/service/app.py", line 35, in <module>
    model = AutoModel.get_model(model_args, tune_strategy='none', ds_config=ds_config, init_method="tcp://localhost:29501")
  File "/data1/xxx/chat/LMFlow/src/lmflow/models/auto_model.py", line 16, in get_model
    return HFDecoderModel(model_args, *args, **kwargs)
  File "/data1/xxx/chat/LMFlow/src/lmflow/models/hf_decoder_model.py", line 232, in __init__
    deepspeed.init_distributed()
  File "/home/xxx/miniconda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/comm/comm.py", line 656, in init_distributed
    cdb = TorchBackend(dist_backend, timeout, init_method, rank, world_size)
  File "/home/xxx/miniconda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/comm/torch.py", line 36, in __init__
    self.init_process_group(backend, timeout, init_method, rank, world_size)
  File "/home/xxx/miniconda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/comm/torch.py", line 40, in init_process_group
    torch.distributed.init_process_group(backend,
  File "/home/xxx/miniconda3/envs/lmflow/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 888, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/xxx/miniconda3/envs/lmflow/lib/python3.9/site-packages/torch/distributed/rendezvous.py", line 245, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
  File "/home/xxxi/miniconda3/envs/lmflow/lib/python3.9/site-packages/torch/distributed/rendezvous.py", line 176, in _create_c10d_store
    return TCPStore(
RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:29500 (errno: 98 - Address already in use). The server socket has failed to bind to 0.0.0.0:29500 (errno: 98 - Address already in use).

**Comment by research4pan** [comment]
Thanks for your interest in LMFlow! I guess the problem is caused by misspecification of master port and master addr. Could you please try set
```sh
export MASTER_ADDR=127.0.0.1
export MASTER_PORT=29500
```
and launch `app.py` again to see if the problem still exists? Thanks 😄

**Comment by lyris** [comment]
CUDA_VISIBLE_DEVICES=0,1 WORLD_SIZE=2 python -m torch.distributed.launch --nproc_per_node=2 --master_port 29500 app.py

**Comment by shizhediao** [comment]
Currently, multi-gpu inference may encounter issues. I'll suggest using a single GPU.

**Comment by gopstrit** [comment]
Do you think it is practically possible to do RAFT on {fine-tuned Falcon-7b} model with {GPT-NEO-7B or DistilBert Reward Model} (which I have already fine-tuned) using 4 GPUs - each 22 GB ?

Tried everything, but it all stops with an error (right after _clean_text and _discard_sample stage.)

**Comment by gopstrit** [comment]
Btw, in my latest run,  the code just stops -without any error - such a silent heartbreak!

![image](https://github.com/OptimalScale/LMFlow/assets/51286679/6f2275f9-ee2f-4280-8088-aea3d6e0f110)

**Comment by gopstrit** [comment]
Hi @shizhediao Thanks for your reply.

I began with single-GPU (~24GB); it stopped in here:
![image](https://github.com/OptimalScale/LMFlow/assets/51286679/44879a54-b257-4552-8525-1258c81889e0)

I then switched to AWS g5x.12 which has 4-GPU / ~24 GB each.

The thing is it loads the fine-tuned model only in GPU-0:

![image](https://github.com/OptimalScale/LMFlow/assets/51286679/708c2d45-1d69-4281-8a30-0731c8541bb2)

Tried loading the model manually to other GPU, manual allocation/feed in data to reward model to fine-tuned model using to.(cuda: 1/2/3). 

But at the following specific code (in raft_trainer.py), the code automatically takes the model back to GPU-0:
![image](https://github.com/OptimalScale/LMFlow/assets/51286679/91e1fd30-f6d9-4b7a-a9c6-f2e71da7de8c)


Yesterday, I tried with both deepseed zero-2 and zero-3: yeah, it doesn't show any error, but simply exits the processs (Screenshot above).

Btw, I also tried using torch.nn.distribution 

![image](https://github.com/OptimalScale/LMFlow/assets/51286679/754ed0a5-7b22-4bce-8e91-0c038b3f60e1)

This is the error I get:

![image](https://github.com/OptimalScale/LMFlow/assets/51286679/90273b60-755e-44f9-a475-b0ef1eeb18f3)

**Comment by shizhediao** [comment]
Could you check the RAM usage?
From the first picture, the killing might be caused by out of RAM

**Comment by gopstrit** [comment]
Btw, I'm testing this on raft_batch_size = 8

For the following: I've first used ds_config_zero2.json

The process stops with CUDA out of memory error
![image](https://github.com/OptimalScale/LMFlow/assets/51286679/1e626446-f621-482c-8350-a755c31dd9de)

This is the exact point where the error occurs (in raft_aligner.py):
![image](https://github.com/OptimalScale/LMFlow/assets/51286679/73322c99-d5c6-4bf2-a80b-3107d2afbfe4)
Following is the resource use just before the error occurs:

![image](https://github.com/OptimalScale/LMFlow/assets/51286679/6c1e4120-640a-4a4f-8bf0-413fb0418a49)

**I also tried to run the code with ds_config_zero3.json**

It stops with following:

![image](https://github.com/OptimalScale/LMFlow/assets/51286679/70a1d8bb-97fc-46f6-8100-8597605d229e)

Memory check before the error:

![image](https://github.com/OptimalScale/LMFlow/assets/51286679/5c8aa754-ea9a-4a92-abca-716e1e6bc0b5)

**Comment by gopstrit** [comment]
I did a quick re-run (With zero-3) to capture the instantaneous cpu/ram usage when the error occurs:

Here's the resourse use (closer to when we get the error: **but hadn't got the error at this point** [_the memory seems to be exhausted here]

![image](https://github.com/OptimalScale/LMFlow/assets/51286679/527cf2f1-f9b9-4220-a1f7-16adae84c01a)

Then the memory comes back again, before the error message comes in

![image](https://github.com/OptimalScale/LMFlow/assets/51286679/07aec470-be78-47fd-8daf-d7d6dc258094)


**So two questions here: 
- do you think this is the issue here?
- do you see any possibility I can still use 4 GPU (24gb each); 'm especilly concerned about the model loading to GPU0 and frying it up. Any idea how we can use all 4 GPU?**

Thank you so much!




_

**Comment by gopstrit** [comment]
@shizhediao Today, I tried running the program in an instance that has higher RAM. (But with same number/size of GPU).

I got pretty similar results.

I also tried running the program using accelerate launch (for which I stripped of the deepspeed line in run_raft.sh; created another test_runner.py file that would execute run_raft.sh and subsequently, raft_align.py).

I configured accelerate with both ds_config_zero2 and ds_config_zero3 as well as without deepspeed.

Also combined with load fine-tuned model with/without 8bit, with/with toech_dtype=torch.bloat16, and with/without device_map = "auto".

This is the result with ds_config_zero2 (without any additional model load settings) (i.e. no 8-bit, torchdtype, etc.) 
(accelerate lauch test_runner.py):

![image](https://github.com/OptimalScale/LMFlow/assets/51286679/004ab697-e86e-42e9-8acf-c8db09ba81e3)

This is the result with ds_config_zero3
![image](https://github.com/OptimalScale/LMFlow/assets/51286679/36924b0c-797a-4d26-a742-77f0ca89a58f)

This is the result with ds_config_zero2 plus additional model load settings (i.e. load in 8bit=true)
![image](https://github.com/OptimalScale/LMFlow/assets/51286679/335d52ec-b0f1-448a-b91b-588dc1cddc31)

**All of the above stops with CUDA OOM error**

Also, tried accelerate launch with ds_config_zero3 (plus, load model in 8bit; and device_map=auto)
This time around, it stops with following error:
![image](https://github.com/OptimalScale/LMFlow/assets/51286679/247a9057-67e2-457d-8be2-647900845c69)

**Comment by shizhediao** [comment]
Seems that CUDA OOM is the problem.
Is it possible to use a GPU with larger memory? May be @WeiXiongUST  could provide some practical suggestions.

**Comment by WeiXiongUST** [comment]
> @shizhediao Today, I tried running the program in an instance that has higher RAM. (But with same number/size of GPU).
> 
> I got pretty similar results.
> 
> I also tried running the program using accelerate launch (for which I stripped of the deepspeed line in run_raft.sh; created another test_runner.py file that would execute run_raft.sh and subsequently, raft_align.py).
> 
> I configured accelerate with both ds_config_zero2 and ds_config_zero3 as well as without deepspeed.
> 
> Also combined with load fine-tuned model with/without 8bit, with/with toech_dtype=torch.bloat16, and with/without device_map = "auto".
> 
> This is the result with ds_config_zero2 (without any additional model load settings) (i.e. no 8-bit, torchdtype, etc.) (accelerate lauch test_runner.py):
> 
> ![image](https://user-images.githubusercontent.com/51286679/259086990-004ab697-e86e-42e9-8acf-c8db09ba81e3.png)
> 
> This is the result with ds_config_zero3 ![image](https://user-images.githubusercontent.com/51286679/259087295-36924b0c-797a-4d26-a742-77f0ca89a58f.png)
> 
> This is the result with ds_config_zero2 plus additional model load settings (i.e. load in 8bit=true) ![image](https://user-images.githubusercontent.com/51286679/259087512-335d52ec-b0f1-448a-b91b-588dc1cddc31.png)
> 
> **All of the above stops with CUDA OOM error**
> 
> Also, tried accelerate launch with ds_config_zero3 (plus, load model in 8bit; and device_map=auto) This time around, it stops with following error: ![image](https://user-images.githubusercontent.com/51286679/259088004-247a9057-67e2-457d-8be2-647900845c69.png)

You may check this issue 545 and try out the separate implementation, which only loads one model at a time to reduce the requirement of memory resource. We shall update the implementation in lmflow soon.

**Comment by shizhediao** [comment]
This issue has been marked as stale because it has not had recent activity. If you think this still needs to be addressed please feel free to reopen this issue. Thanks
