### ISSUE TITLE
run app.py报错

### ISSUE THREAD

**Issue by txiang163** [OptimalScale/LMFlow#204]
在运行app.py时出现以下错误
(my_lm) xt@ji-jupyter-6713700621420699648-master-0:~/txiang/LMFlow/service$ python app.py
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Failed to use RAM optimized load. Automatically use original load instead.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "/home/xt/txiang/LMFlow/service/../src/lmflow/models/hf_decoder_model.py", line 192, in __init__
    self.backend_model = AutoModelForCausalLM.from_pretrained(
  File "/home/xt/anaconda3/envs/my_lm/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 474, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers_modules.configuration_chatglm.ChatGLMConfig'> for this kind of AutoModel: AutoModelForCausalLM.
Model type should be one of BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, CodeGenConfig, CTRLConfig, Data2VecTextConfig, ElectraConfig, ErnieConfig, GitConfig, GPT2Config, GPT2Config, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, LlamaConfig, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MvpConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, Speech2Text2Config, TransfoXLConfig, TrOCRConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig.

我是在hugging face models里面把chatglm下载下来放到了output_models目录下，运行的时候说无法识别ChatGLMConfig这个配置类，这个问题该如何解决？

**Comment by research4pan** [comment]
Thanks for your interest in LMFlow! Currently we haven't merged the support for chatglm yet. The corresponding pull request is [this one](https://github.com/OptimalScale/LMFlow/pull/152). We will let you know once the merge is completed. Thanks for your understanding 🙏

**Comment by txiang163** [comment]
So what are the models on huggingface that you currently support?

**Comment by research4pan** [comment]
We support all decoder-only models in huggingface, such as gpt2, gpt2-large, gpt2-xl, gpt-neo-2.7b, galactica, bloom, llama etc. The aforementioned pull request will introduce more supports of all encoder-decoder models in huggingface, such as T5. Hope that answers your question. Thanks 😄

**Comment by txiang163** [comment]
I have downloaded gpt-neo-2.7b from huggingface ,and put it in the folder /output_models and run the code in the /script folder:  bash run_chatbot.sh ../output_models/GPT-Neo2.7B/, and it generated the below problem:

Traceback (most recent call last):
  File "/home/xt/txiang/LMFlow/scripts/../examples/chatbot.py", line 118, in <module>
    main()
  File "/home/xt/txiang/LMFlow/scripts/../examples/chatbot.py", line 45, in main
    model = AutoModel.get_model(
  File "/home/xt/txiang/LMFlow/scripts/../src/lmflow/models/auto_model.py", line 14, in get_model
    return HFDecoderModel(model_args, *args, **kwargs)
  File "/home/xt/txiang/LMFlow/scripts/../src/lmflow/models/hf_decoder_model.py", line 218, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(model_args.model_name_or_path,trust_remote_code=True)
  File "/home/xt/anaconda3/envs/my_lm/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 694, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/xt/anaconda3/envs/my_lm/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1811, in from_pretrained
    return cls._from_pretrained(
  File "/home/xt/anaconda3/envs/my_lm/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1841, in _from_pretrained
    slow_tokenizer = (cls.slow_tokenizer_class)._from_pretrained(
  File "/home/xt/anaconda3/envs/my_lm/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1965, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/xt/anaconda3/envs/my_lm/lib/python3.9/site-packages/transformers/models/gpt2/tokenization_gpt2.py", line 188, in __init__
    with open(vocab_file, encoding="utf-8") as vocab_handle:
TypeError: expected str, bytes or os.PathLike object, not NoneType

How to solve it, thanks for your reply.

**Comment by research4pan** [comment]
As for the issue not displayed here (but in my mailbox), you may run the `./scripts/run_chatbot.sh` under the project directory. Running it under `./scripts` may result in a model-not-found error. Hope that helps. Thanks~

**Comment by shizhediao** [comment]
This issue has been marked as stale because it has not had recent activity. If you think this still needs to be addressed please feel free to reopen this issue. Thanks
