### ISSUE TITLE
How to run other models with app.py

### ISSUE THREAD

**Issue by george66s** [OptimalScale/LMFlow#211]
Hi,

I am trying to run a model with app.py but not successful. Below is my app.py content that I have modified.

model_name_or_path = "/home/gsvr1/Datasets_Com/Models/llama-13b-hf"
lora_path = '../output_models/instruction_ckpt/llama13b-lora-380k/'
model_args = ModelArguments(model_name_or_path=model_name_or_path, use_ram_optimized_load=False, lora_alpha=lora_path)

Below are the error messages when I launch app.py:

/home/gsvr1/anaconda3/envs/lmflow/bin/python3.9 /home/gsvr1/Projects/workspace_AI/LMFlow/service/app.py 
Loading checkpoint shards: 100%|██████████| 41/41 [00:47<00:00,  1.15s/it]
Traceback (most recent call last):
  File "/home/gsvr1/Projects/workspace_AI/LMFlow/service/app.py", line 37, in <module>
    model = AutoModel.get_model(model_args, tune_strategy='none', ds_config=ds_config)
  File "/home/gsvr1/Projects/workspace_AI/LMFlow/src/lmflow/models/auto_model.py", line 16, in get_model
    return HFDecoderModel(model_args, *args, **kwargs)
  File "/home/gsvr1/Projects/workspace_AI/LMFlow/src/lmflow/models/hf_decoder_model.py", line 224, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(model_args.model_name_or_path)
  File "/home/gsvr1/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 691, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class LLaMATokenizer does not exist or is not currently imported.

Process finished with exit code 1

Could you please help where I did not do correctly?

Thanks
George

**Comment by SHUMKASHUN** [comment]
Hi,
    This is because your model checkpoint has tokenizer name of LLaMATokenizer which does not match your transformers package (LlamaTokenizer). You may try download a new model (e.g. pinkmanlove/llama-13b-hf) instead.

**Comment by shizhediao** [comment]
This issue has been marked as stale because it has not had recent activity. If you think this still needs to be addressed please feel free to reopen this issue. Thanks
