### ISSUE TITLE
when I try to fine tune 

### ISSUE THREAD

**Issue by ChrisXULC** [OptimalScale/LMFlow#226]
Traceback (most recent call last):
  File "/root/LMFlow/new/LMFlow-main/examples/finetune.py", line 70, in <module>
    main()
  File "/root/LMFlow/new/LMFlow-main/examples/finetune.py", line 55, in main
    model = AutoModel.get_model(model_args)
  File "/root/LMFlow/new/LMFlow-main/examples/lmflow/models/auto_model.py", line 16, in get_model
    return HFDecoderModel(model_args, *args, **kwargs)
  File "/root/LMFlow/new/LMFlow-main/examples/lmflow/models/hf_decoder_model.py", line 148, in __init__
    model = AutoModelForCausalLM.from_pretrained(
  File "/root/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "/root/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2709, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/root/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3087, in _load_pretrained_model
    raise RuntimeError(f"Error(s) in loading state_dict for {model.__class__.__name__}:\n\t{error_msg}")
RuntimeError: Error(s) in loading state_dict for LlamaForCausalLM:
	size mismatch for model.embed_tokens.weight: copying a param with shape torch.Size([49954, 5120]) from checkpoint, the shape in current model is torch.Size([32000, 5120]).
	size mismatch for lm_head.weight: copying a param with shape torch.Size([49954, 5120]) from checkpoint, the shape in current model is torch.Size([32000, 5120]).
	You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.

**Comment by research4pan** [comment]
Thanks for your interest in LMFlow! Looks like the input model doesn't match the llama structure. Could you please provide the commandline arguments so we may check that for you? Thanks 😄

**Comment by shizhediao** [comment]
This issue has been marked as stale because it has not had recent activity. If you think this still needs to be addressed please feel free to reopen this issue. Thanks

**Comment by boxbox-0427** [comment]
@shizhediao Hi, I got the same error with [this model](https://huggingface.co/AlexeyChe/llama-30b-lora/tree/main), while this error would not appear with [7b-model](https://huggingface.co/AlexeyChe/llama-7b-lora).

**Comment by shizhediao** [comment]
We do not know what these models are as they are provided by someone else.
If you want to use lora, you can download our trained lora checkpoints here https://github.com/OptimalScale/LMFlow#5-model-release
Thanks!
