### ISSUE TITLE
How to run finetuning on server without internet connection

### ISSUE THREAD

**Issue by szl666** [OptimalScale/LMFlow#250]
I ran the finetuning with lora on my server without internet connection, the following error appears:

Traceback (most recent call last):
  File "/fs0/home/liqiang/anaconda3/envs/lmflow/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/fs0/home/liqiang/anaconda3/envs/lmflow/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/fs0/home/liqiang/anaconda3/envs/lmflow/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/fs0/home/liqiang/anaconda3/envs/lmflow/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/fs0/home/liqiang/anaconda3/envs/lmflow/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/fs0/home/liqiang/anaconda3/envs/lmflow/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/fs0/home/liqiang/anaconda3/envs/lmflow/lib/python3.9/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/fs0/home/liqiang/anaconda3/envs/lmflow/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x2afc97e66820>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/fs0/home/liqiang/anaconda3/envs/lmflow/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/fs0/home/liqiang/anaconda3/envs/lmflow/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/fs0/home/liqiang/anaconda3/envs/lmflow/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/llama_hf/llama-7b-hf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2afc97e66820>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/fs0/home/liqiang/LMFlow/examples/finetune.py", line 76, in <module>
    main()
  File "/fs0/home/liqiang/LMFlow/examples/finetune.py", line 72, in main
    tuned_model = finetuner.tune(model=model, lm_dataset=lm_dataset)
  File "/fs0/home/liqiang/LMFlow/src/lmflow/pipeline/finetuner.py", line 266, in tune
    trainer.create_model_card(**kwargs)
  File "/fs0/home/liqiang/LMFlow/transformers-main/src/transformers/trainer.py", line 3562, in create_model_card
    training_summary = TrainingSummary.from_trainer(
  File "/fs0/home/liqiang/LMFlow/transformers-main/src/transformers/modelcard.py", line 610, in from_trainer
    return cls(
  File "<string>", line 17, in __init__
  File "/fs0/home/liqiang/LMFlow/transformers-main/src/transformers/modelcard.py", line 385, in __post_init__
    info = model_info(self.finetuned_from)
  File "/fs0/home/liqiang/anaconda3/envs/lmflow/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/fs0/home/liqiang/anaconda3/envs/lmflow/lib/python3.9/site-packages/huggingface_hub/hf_api.py", line 1623, in model_info
    r = requests.get(path, headers=headers, timeout=timeout, params=params)
  File "/fs0/home/liqiang/anaconda3/envs/lmflow/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/fs0/home/liqiang/anaconda3/envs/lmflow/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/fs0/home/liqiang/anaconda3/envs/lmflow/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/fs0/home/liqiang/anaconda3/envs/lmflow/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/fs0/home/liqiang/anaconda3/envs/lmflow/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/llama_hf/llama-7b-hf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2afc97e66820>: Failed to establish a new connection: [Errno -2] Name or service not known'))

**Comment by shizhediao** [comment]
Hi,
You may look into the code line 266 in this file.
`File "/fs0/home/liqiang/LMFlow/src/lmflow/pipeline/finetuner.py"`

Commenting out line 264-266 may help.

**Comment by szl666** [comment]
Thank you very much, this solved my error.

**Comment by shizhediao** [comment]
You are welcome!
