### ISSUE TITLE
Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops.

### ISSUE THREAD

**Issue by ChenWenKai8023ni** [OptimalScale/LMFlow#282]
在执行  pip install -e . 命令报错
 Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\11655\AppData\Local\Temp\pip-install-lbtscf83\deepspeed_2606a16b880f42699029a68bee453a56\setup.py", line 122, in <module>
          assert torch_available, "Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops."
      AssertionError: Unable to pre-compile ops without torch installed. Please install torch before attempting to pre-compile ops.
      [WARNING] Unable to import torch, pre-compiling ops will be disabled. Please visit https://pytorch.org/ to see how to properly install torch on your system.
       [WARNING]  unable to import torch, please install it if you want to pre-compile any deepspeed ops.
      DS_BUILD_OPS=1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by shizhediao** [comment]
我们只在linux系统进行过完整的测试，推荐使用linux系统。
这个错误是因为缺少pytorch，可以参考官网安装 https://pytorch.org/

**Comment by shizhediao** [comment]
This issue has been marked as stale because it has not had recent activity. If you think this still needs to be addressed please feel free to reopen this issue. Thanks

**Comment by AIDevMonster** [comment]
thank you so much, shizhediao. 🗡️
