### ISSUE TITLE
outputmodel 中没有pytorch_model.bin

### ISSUE THREAD

**Issue by NingBoHao** [OptimalScale/LMFlow#301]
(lmflow) PS E:\LMFlow-main\LMFlow-main> bash .\scripts\run_chatbot.sh .\output_models\llama7b-lora-medical\  .\output_models\llama7b-lora-medical\llama7b-lora-medical\
[2023-04-24 22:59:26,646] [WARNING] [runner.py:190:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
Detected CUDA_VISIBLE_DEVICES=0: setting --include=localhost:0
[2023-04-24 22:59:26,667] [INFO] [runner.py:540:main] cmd = D:\UserSoftware\Anaconda3\envs\lmflow\python.exe -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None examples/chatbot.py --deepspeed configs/ds_config_chatbot.json --model_name_or_path .\output_models\llama7b-lora-medical\ --lora_model_path .\output_models\llama7b-lora-medical\llama7b-lora-medical\
[2023-04-24 22:59:28,342] [INFO] [launch.py:229:main] WORLD INFO DICT: {'localhost': [0]}
[2023-04-24 22:59:28,342] [INFO] [launch.py:235:main] nnodes=1, num_local_procs=1, node_rank=0
[2023-04-24 22:59:28,343] [INFO] [launch.py:246:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2023-04-24 22:59:28,346] [INFO] [launch.py:247:main] dist_world_size=1
[2023-04-24 22:59:28,346] [INFO] [launch.py:249:main] Setting CUDA_VISIBLE_DEVICES=0
configs/ds_config_chatbot.json
Traceback (most recent call last):
  File "E:\LMFlow-main\LMFlow-main\examples\chatbot.py", line 155, in <module>
    main()
  File "E:\LMFlow-main\LMFlow-main\examples\chatbot.py", line 69, in main
    model = AutoModel.get_model(
  File "e:\lmflow-main\lmflow-main\src\lmflow\models\auto_model.py", line 16, in get_model
    return HFDecoderModel(model_args, *args, **kwargs)
  File "e:\lmflow-main\lmflow-main\src\lmflow\models\hf_decoder_model.py", line 225, in __init__
    self.backend_model = AutoModelForCausalLM.from_pretrained(
  File "D:\UserSoftware\Anaconda3\envs\lmflow\lib\site-packages\transformers\models\auto\auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "D:\UserSoftware\Anaconda3\envs\lmflow\lib\site-packages\transformers\modeling_utils.py", line 2405, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory .\output_models\llama7b-lora-medical\.
[2023-04-24 22:59:31,371] [INFO] [launch.py:428:sigkill_handler] Killing subprocess 1572
[2023-04-24 22:59:31,378] [ERROR] [launch.py:434:sigkill_handler] ['D:\\UserSoftware\\Anaconda3\\envs\\lmflow\\python.exe', '-u', 'examples/chatbot.py', '--local_rank=0', '--deepspeed', 'configs/ds_config_chatbot.json', '--model_name_or_path', '.\\output_models\\llama7b-lora-medical\\', '--lora_model_path', '.\\output_models\\llama7b-lora-medical\\llama7b-lora-medical\\'] exits with return code = 1

**Comment by NingBoHao** [comment]
![image](https://user-images.githubusercontent.com/51772602/234045412-ba1079cd-1dc3-4131-b377-33a009ce2223.png)

**Comment by NingBoHao** [comment]
下载后运行的出现的问题
![image](https://user-images.githubusercontent.com/51772602/234045724-fea6ab85-3422-46cc-9b3f-794ac629adfb.png)

**Comment by shizhediao** [comment]
What's the error message?

**Comment by shizhediao** [comment]
This issue has been marked as stale because it has not had recent activity. If you think this still needs to be addressed please feel free to reopen this issue. Thanks
