### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '.\\output_models\\llama_7b_lora\\7B\\params.json'

### ISSUE THREAD

**Issue by NingBoHao** [OptimalScale/LMFlow#302]
(lmflow) PS E:\LMFlow-main\LMFlow-main> python ./scripts/convert_llama_weights_to_hf.py --input_dir  .\output_models\llama_7b_lora\ --model_size 7B --output_dir .\output_models\llama-7b-hf\
Traceback (most recent call last):
  File "E:\LMFlow-main\LMFlow-main\scripts\convert_llama_weights_to_hf.py", line 279, in <module>
    main()
  File "E:\LMFlow-main\LMFlow-main\scripts\convert_llama_weights_to_hf.py", line 267, in main
    write_model(
  File "E:\LMFlow-main\LMFlow-main\scripts\convert_llama_weights_to_hf.py", line 80, in write_model
    params = read_json(os.path.join(input_base_path, "params.json"))
  File "E:\LMFlow-main\LMFlow-main\scripts\convert_llama_weights_to_hf.py", line 66, in read_json
    with open(path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '.\\output_models\\llama_7b_lora\\7B\\params.json'
(lmflow) PS E:\LMFlow-main\LMFlow-main>

**Comment by shizhediao** [comment]
To download the model, please go to the 'output_models' folder and execute 'bash download.sh all'.

**Comment by NingBoHao** [comment]
下载之后出现的
![image](https://user-images.githubusercontent.com/51772602/234046106-6bd5429b-a75f-4cf7-bdb5-87f0f3f0c611.png)

**Comment by NingBoHao** [comment]
![image](https://user-images.githubusercontent.com/51772602/234047660-aa4284f5-73bc-40af-a688-ab22b7939902.png)

**Comment by shizhediao** [comment]
Please refer to our Chinese version documentation for more information about setting up and tuning models. Thanks https://github.com/OptimalScale/LMFlow/blob/main/readme/README_zh-hans.md

**Comment by shizhediao** [comment]
This issue has been marked as stale because it has not had recent activity. If you think this still needs to be addressed please feel free to reopen this issue. Thanks
