### ISSUE TITLE
[BUG] colab运行!source ./scripts/run_finetune.sh出现错误，怎么修改

### ISSUE THREAD

**Issue by Gera001** [OptimalScale/LMFlow#304]
[2023-04-24 16:32:24,796] [WARNING] [runner.py:186:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
Traceback (most recent call last):
  File "/usr/local/bin/deepspeed", line 6, in <module>
    main()
  File "/usr/local/lib/python3.10/site-packages/deepspeed/launcher/runner.py", line 411, in main
    raise RuntimeError("Unable to proceed, no GPU resources available")
RuntimeError: Unable to proceed, no GPU resources available

**Comment by shizhediao** [comment]
It requires GPU to run fine-tuning process. It seems that your machine does not have GPU.
Could you run the program on a GPU machine?  Thanks~

**Comment by Gera001** [comment]
google colab呀还是GPU类型的为什么会没有



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月25日(周二) 上午10:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [OptimalScale/LMFlow] [BUG] colab运行!source ./scripts/run_finetune.sh出现错误，怎么修改 (Issue #304)




 
It requires GPU to run fine-tuning process. It seems that your machine does not have GPU.
 Could you run the program on a GPU machine?  Thanks~

**Comment by shizhediao** [comment]
`RuntimeError: Unable to proceed, no GPU resources available `  这个error message看起来是说没有GPU。
可以用`nvidia-smi` 检查一下

**Comment by shizhediao** [comment]
This issue has been marked as stale because it has not had recent activity. If you think this still needs to be addressed please feel free to reopen this issue. Thanks
