### ISSUE TITLE
[BUG]No module named 'lmflow'

### ISSUE THREAD

**Issue by standy2007** [OptimalScale/LMFlow#305]
(lmflow) [root@localhost service]# python app.py 
Traceback (most recent call last):
  File "/home/LMFlow/service/app.py", line 4, in <module>
    from lmflow.datasets.dataset import Dataset
ModuleNotFoundError: No module named 'lmflow'

**Comment by shizhediao** [comment]
Please install `lmflow` first referring to https://github.com/OptimalScale/LMFlow#1setup

**Comment by standy2007** [comment]
I have installed lmflow at first step.

**Comment by shizhediao** [comment]
Could you check the dependencies install via `pip list`? and it would be better if you could copy and paste such information here

**Comment by haley05-cloud** [comment]
[2023-05-26 05:49:38,203] [INFO] [launch.py:163:main] dist_world_size=8
[2023-05-26 05:49:38,203] [INFO] [launch.py:165:main] Setting CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
Traceback (most recent call last):
  File "/home/user01/.cache1/LMFlow/examples/finetune.py", line 22, in <module>
    from lmflow.args import (
ModuleNotFoundError: No module named 'lmflow'
Traceback (most recent call last):
  File "/home/user01/.cache1/LMFlow/examples/finetune.py", line 22, in <module>
    from lmflow.args import (
ModuleNotFoundError: No module named 'lmflow'
Traceback (most recent call last):
  File "/home/user01/.cache1/LMFlow/examples/finetune.py", line 22, in <module>
    from lmflow.args import (
ModuleNotFoundError: No module named 'lmflow'
Traceback (most recent call last):
  File "/home/user01/.cache1/LMFlow/examples/finetune.py", line 22, in <module>
    from lmflow.args import (
ModuleNotFoundError: No module named 'lmflow'
Traceback (most recent call last):
  File "/home/user01/.cache1/LMFlow/examples/finetune.py", line 22, in <module>
    from lmflow.args import (
ModuleNotFoundError: No module named 'lmflow'
Traceback (most recent call last):
  File "/home/user01/.cache1/LMFlow/examples/finetune.py", line 22, in <module>
    from lmflow.args import (
ModuleNotFoundError: No module named 'lmflow'
Traceback (most recent call last):
  File "/home/user01/.cache1/LMFlow/examples/finetune.py", line 22, in <module>
    from lmflow.args import (
ModuleNotFoundError: No module named 'lmflow'
Traceback (most recent call last):
  File "/home/user01/.cache1/LMFlow/examples/finetune.py", line 22, in <module>
    from lmflow.args import (
ModuleNotFoundError: No module named 'lmflow'
[2023-05-26 05:49:39,206] [INFO] [launch.py:314:sigkill_handler] Killing subprocess 2094170
[2023-05-26 05:49:39,224] [INFO] [launch.py:314:sigkill_handler] Killing subprocess 2094171
[2023-05-26 05:49:39,239] [INFO] [launch.py:314:sigkill_handler] Killing subprocess 2094172
[2023-05-26 05:49:39,239] [INFO] [launch.py:314:sigkill_handler] Killing subprocess 2094173
[2023-05-26 05:49:39,253] [INFO] [launch.py:314:sigkill_handler] Killing subprocess 2094174
[2023-05-26 05:49:39,267] [INFO] [launch.py:314:sigkill_handler] Killing subprocess 2094175
[2023-05-26 05:49:39,280] [INFO] [launch.py:314:sigkill_handler] Killing subprocess 2094176
[2023-05-26 05:49:39,293] [INFO] [launch.py:314:sigkill_handler] Killing subprocess 2094177
[2023-05-26 05:49:39,307] [ERROR] [launch.py:320:sigkill_handler] ['/usr/bin/python3.10', '-u', 'examples/finetune.py', '--local_rank=7', '--model_name_or_path', 'gpt2', '--dataset_path', '/home/user01/.cache1/LMFlow/data/alpaca/train', '--output_dir', '/home/user01/.cache1/LMFlow/output_models/finetune', '--overwrite_output_dir', '--num_train_epochs', '0.01', '--learning_rate', '2e-5', '--block_size', '512', '--per_device_train_batch_size', '1', '--deepspeed', 'configs/ds_config_zero3.json', '--bf16', '--run_name', 'finetune', '--validation_split_percentage', '0', '--logging_steps', '20', '--do_train', '--ddp_timeout', '72000', '--save_steps', '5000', '--dataloader_num_workers', '1'] exits with return code = 1

pip list |grep lmflow
lmflow                   0.0.1
 pip3 list |grep lmflow
lmflow                   0.0.1
