### ISSUE TITLE
python .\app.py    运行出现错误

### ISSUE THREAD

**Issue by NingBoHao** [OptimalScale/LMFlow#308]
(lmflow) PS E:\LMFlow-main\LMFlow-main\service> python .\app.py
[2023-04-25 21:05:12,655] [INFO] [comm.py:570:init_distributed] Not using the DeepSpeed or dist launchers, attempting to detect MPI environment...
'"hostname -I"' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Traceback (most recent call last):
  File "E:\LMFlow-main\LMFlow-main\service\app.py", line 34, in <module>
    model = AutoModel.get_model(model_args, tune_strategy='none', ds_config=ds_config)
  File "e:\lmflow-main\lmflow-main\src\lmflow\models\auto_model.py", line 16, in get_model
    return HFDecoderModel(model_args, *args, **kwargs)
  File "e:\lmflow-main\lmflow-main\src\lmflow\models\hf_decoder_model.py", line 237, in __init__
    deepspeed.init_distributed()
  File "D:\UserSoftware\Anaconda3\envs\lmflow\lib\site-packages\deepspeed\comm\comm.py", line 576, in init_distributed
    mpi_discovery(distributed_port=distributed_port, verbose=verbose)
  File "D:\UserSoftware\Anaconda3\envs\lmflow\lib\site-packages\deepspeed\comm\comm.py", line 604, in mpi_discovery
    result = subprocess.check_output(hostname_cmd, shell=True)
  File "D:\UserSoftware\Anaconda3\envs\lmflow\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "D:\UserSoftware\Anaconda3\envs\lmflow\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['hostname -I']' returned non-zero exit status 1.

**Comment by NingBoHao** [comment]
记录下修改代码
![image](https://user-images.githubusercontent.com/51772602/234298561-0c14ac16-5cc7-4f06-9651-fb0a350d3960.png)

**Comment by NingBoHao** [comment]
紧接着出现问题
no NCCL 
解决
![image](https://user-images.githubusercontent.com/51772602/234305101-672d9980-66f6-4319-9a6e-4337f753b616.png)
https://huaweicloud.csdn.net/63806cdbdacf622b8df87fbe.html?spm=1001.2101.3001.6650.1&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7EBlogCommendFromBaidu%7Eactivity-1-120070425-blog-127900544.235%5Ev32%5Epc_relevant_default_base3&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7EBlogCommendFromBaidu%7Eactivity-1-120070425-blog-127900544.235%5Ev32%5Epc_relevant_default_base3&utm_relevant_index=2

**Comment by shizhediao** [comment]
看起来您是在windows下运行的，建议使用linux服务器运行。我们没有在windows下进行过测试。欢迎加入社区群寻求更多的帮助。
----
It looks like you're running on Windows, and we recommend using a Linux server to run. We haven't tested on Windows. Feel free to join the community group for more help.

**Comment by shizhediao** [comment]
This issue has been marked as stale because it has not had recent activity. If you think this still needs to be addressed please feel free to reopen this issue. Thanks

**Comment by Miamas777** [comment]
I have the same problem.
