### ISSUE TITLE
use self-trained lora model run chatbot.py Error

### ISSUE THREAD

**Issue by mengjiexu** [OptimalScale/LMFlow#340]
I use  scripts/run_finetune_with_lora_save_aggregated_weights.sh to train the llama-7b model, after training ,the saved results don't have adapter_config.json and cannot use chatbot.py to load

**Comment by shizhediao** [comment]
After running `scripts/run_finetune_with_lora_save_aggregated_weights.sh `, the output will be a new full model (without lora) because the lora has been merged into the full model.
Therefore, during inference, you do not need a lora adapter anymore. Just need to set `model_name_or_path` without `lora_model_path`

**Comment by mengjiexu** [comment]
when I run use:  bash scripts/run_chatbot.py output_models/finetune_with_lora_xmj_text2text2，
bug is：
Traceback (most recent call last):
  File "/home/xmj/mycipan3/ChatGPT_xmj/LMFlow/examples/chatbot.py", line 155, in <module>
    main()
  File "/home/xmj/mycipan3/ChatGPT_xmj/LMFlow/examples/chatbot.py", line 69, in main
    model = AutoModel.get_model(
  File "/home/xmj/mycipan3/ChatGPT_xmj/LMFlow/src/lmflow/models/auto_model.py", line 16, in get_model
    return HFDecoderModel(model_args, *args, **kwargs)
  File "/home/xmj/mycipan3/ChatGPT_xmj/LMFlow/src/lmflow/models/hf_decoder_model.py", line 244, in __init__
    self.ds_engine = deepspeed.initialize(model=self.backend_model, config_params=ds_config)[0]
  File "/home/xmj/anaconda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/__init__.py", line 125, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/xmj/anaconda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 297, in __init__
    self._configure_distributed_model(model)
  File "/home/xmj/anaconda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1146, in _configure_distributed_model
    self.module.to(self.device)
  File "/home/xmj/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/modeling_utils.py", line 1861, in to
    return super().to(*args, **kwargs)
  File "/home/xmj/anaconda3/envs/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/home/xmj/anaconda3/envs/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/xmj/anaconda3/envs/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/xmj/anaconda3/envs/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/home/xmj/anaconda3/envs/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/home/xmj/anaconda3/envs/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!
[2023-04-29 17:21:06,715] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 815874
[2023-04-29 17:21:06,716] [ERROR] [launch.py:324:sigkill_handler] ['/home/xmj/anaconda3/envs/lmflow/bin/python', '-u', 'examples/chatbot.py', '--local_rank=0', '--deepspeed', 'configs/ds_config_chatbot.json', '--model_name_or_path', '/home/xmj/mycipan3/ChatGPT_xmj/LMFlow/output_models/finetune_with_lora_xmj_text2text2'] exits with return code = 1

**Comment by shizhediao** [comment]
This issue could be solved by setting `--use_ram_optimized_load False `.

Please refer to https://github.com/OptimalScale/LMFlow/issues/49 and https://github.com/OptimalScale/LMFlow/issues/154
