### ISSUE TITLE
[BUG] BUG in run_finetune.sh

### ISSUE THREAD

**Issue by Ancientshi** [OptimalScale/LMFlow#374]
**Describe the bug**
I have met bugs in run_finetune.sh, the logs are as follows:
(I am using CUDA11.7)
```
bash run_finetune.sh
[2023-05-07 20:15:45,744] [WARNING] [runner.py:186:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2023-05-07 20:15:45,765] [INFO] [runner.py:550:main] cmd = /home/yunxshi/anaconda3/envs/lmflow2/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMV19 --master_addr=127.0.0.1 --master_port=11000 --enable_each_rank_log=None ../examples/finetune.py --model_name_or_path gpt2 --dataset_path /home/yunxshi/Data/workspace/LMflow/LMFlow-main/data/AIducation/train --output_dir /home/yunxshi/Data/workspace/LMflow/LMFlow-main/output_models/AIducation_finetune --overwrite_output_dir --num_train_epochs 0.01 --learning_rate 2e-5 --block_size 512 --per_device_train_batch_size 1 --deepspeed ../configs/ds_config_zero3.json --fp16 --run_name finetune --validation_split_percentage 0 --logging_steps 20 --do_train --ddp_timeout 72000 --save_steps 5000 --dataloader_num_workers 1
[2023-05-07 20:15:49,023] [INFO] [launch.py:142:main] WORLD INFO DICT: {'localhost': [0, 1]}
[2023-05-07 20:15:49,023] [INFO] [launch.py:148:main] nnodes=1, num_local_procs=2, node_rank=0
[2023-05-07 20:15:49,023] [INFO] [launch.py:161:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1]})
[2023-05-07 20:15:49,023] [INFO] [launch.py:162:main] dist_world_size=2
[2023-05-07 20:15:49,023] [INFO] [launch.py:164:main] Setting CUDA_VISIBLE_DEVICES=0,1
[2023-05-07 20:15:59,387] [INFO] [comm.py:652:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
05/07/2023 20:15:59 - WARNING - lmflow.pipeline.finetuner - Process rank: 0, device: cuda:0, n_gpu: 1distributed training: True, 16-bits training: True
05/07/2023 20:16:00 - WARNING - lmflow.pipeline.finetuner - Process rank: 1, device: cuda:1, n_gpu: 1distributed training: True, 16-bits training: True
05/07/2023 20:16:01 - WARNING - datasets.builder - Found cached dataset json (/home/yunxshi/.cache/huggingface/datasets/json/default-cc1b956fdbc444c6/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51)
05/07/2023 20:16:01 - WARNING - datasets.builder - Found cached dataset json (/home/yunxshi/.cache/huggingface/datasets/json/default-cc1b956fdbc444c6/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51)
[2023-05-07 20:16:07,096] [INFO] [partition_parameters.py:415:__exit__] finished initializing model with 0.16B parameters
/home/yunxshi/anaconda3/envs/lmflow2/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py:2547: UserWarning: torch.distributed._all_gather_base is a private function and will be deprecated. Please use torch.distributed.all_gather_into_tensor instead.
  warnings.warn(
/home/yunxshi/anaconda3/envs/lmflow2/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py:2547: UserWarning: torch.distributed._all_gather_base is a private function and will be deprecated. Please use torch.distributed.all_gather_into_tensor instead.
  warnings.warn(
05/07/2023 20:16:08 - WARNING - datasets.fingerprint - Parameter 'function'=<function HFDecoderModel.tokenize.<locals>.tokenize_function at 0x2ab697ce1790> of the transform datasets.arrow_dataset.Dataset._map_single couldn't be hashed properly, a random hash was used instead. Make sure your transforms and parameters are serializable with pickle or dill for the dataset fingerprinting and caching to work. If you reuse this transform, the caching mechanism will consider it to be different from the previous calls and recompute everything. This warning is only showed once. Subsequent hashing failures won't be showed.
05/07/2023 20:16:08 - WARNING - datasets.arrow_dataset - Loading cached processed dataset at /home/yunxshi/.cache/huggingface/datasets/json/default-cc1b956fdbc444c6/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-1c80317fa3b1799d.arrow
05/07/2023 20:16:08 - WARNING - datasets.arrow_dataset - Loading cached processed dataset at /home/yunxshi/.cache/huggingface/datasets/json/default-cc1b956fdbc444c6/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-fa5d5653a4dcda14.arrow
05/07/2023 20:16:08 - WARNING - datasets.fingerprint - Parameter 'function'=<function HFDecoderModel.tokenize.<locals>.tokenize_function at 0x2b66f607c790> of the transform datasets.arrow_dataset.Dataset._map_single couldn't be hashed properly, a random hash was used instead. Make sure your transforms and parameters are serializable with pickle or dill for the dataset fingerprinting and caching to work. If you reuse this transform, the caching mechanism will consider it to be different from the previous calls and recompute everything. This warning is only showed once. Subsequent hashing failures won't be showed.
05/07/2023 20:16:08 - WARNING - datasets.arrow_dataset - Loading cached processed dataset at /home/yunxshi/.cache/huggingface/datasets/json/default-cc1b956fdbc444c6/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-1c80317fa3b1799d.arrow
05/07/2023 20:16:08 - WARNING - datasets.arrow_dataset - Loading cached processed dataset at /home/yunxshi/.cache/huggingface/datasets/json/default-cc1b956fdbc444c6/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51/cache-fa5d5653a4dcda14.arrow
Using /home/yunxshi/.cache/torch_extensions/py39_cu117 as PyTorch extensions root...
Using /home/yunxshi/.cache/torch_extensions/py39_cu117 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/yunxshi/.cache/torch_extensions/py39_cu117/cpu_adam/build.ninja...
Building extension module cpu_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] c++ cpu_adam.o custom_cuda_kernel.cuda.o -shared -lcurand -L/home/yunxshi/anaconda3/envs/lmflow2/lib/python3.9/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda -ltorch -ltorch_python -L/home/yunxshi/anaconda3/envs/lmflow2/lib64 -lcudart -o cpu_adam.so
FAILED: cpu_adam.so 
c++ cpu_adam.o custom_cuda_kernel.cuda.o -shared -lcurand -L/home/yunxshi/anaconda3/envs/lmflow2/lib/python3.9/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda -ltorch -ltorch_python -L/home/yunxshi/anaconda3/envs/lmflow2/lib64 -lcudart -o cpu_adam.so
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: cannot find -lcurand
/opt/rh/devtoolset-11/root/usr/libexec/gcc/x86_64-redhat-linux/11/ld: cannot find -lcudart
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/yunxshi/anaconda3/envs/lmflow2/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/home/yunxshi/anaconda3/envs/lmflow2/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/yunxshi/workspace/LMflow/LMFlow-main/scripts/../examples/finetune.py", line 61, in <module>
    main()
  File "/data/yunxshi/workspace/LMflow/LMFlow-main/scripts/../examples/finetune.py", line 57, in main
    tuned_model = finetuner.tune(model=model, dataset=dataset)
  File "/data/yunxshi/workspace/LMflow/LMFlow-main/src/lmflow/pipeline/finetuner.py", line 274, in tune
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/yunxshi/anaconda3/envs/lmflow2/lib/python3.9/site-packages/transformers/trainer.py", line 1639, in train
    return inner_training_loop(
  File "/home/yunxshi/anaconda3/envs/lmflow2/lib/python3.9/site-packages/transformers/trainer.py", line 1708, in _inner_training_loop
    deepspeed_engine, optimizer, lr_scheduler = deepspeed_init(
  File "/home/yunxshi/anaconda3/envs/lmflow2/lib/python3.9/site-packages/transformers/deepspeed.py", line 378, in deepspeed_init
    deepspeed_engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/home/yunxshi/anaconda3/envs/lmflow2/lib/python3.9/site-packages/deepspeed/__init__.py", line 125, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/yunxshi/anaconda3/envs/lmflow2/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 340, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/yunxshi/anaconda3/envs/lmflow2/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1283, in _configure_optimizer
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/home/yunxshi/anaconda3/envs/lmflow2/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1354, in _configure_basic_optimizer
    optimizer = DeepSpeedCPUAdam(model_parameters,
  File "/home/yunxshi/anaconda3/envs/lmflow2/lib/python3.9/site-packages/deepspeed/ops/adam/cpu_adam.py", line 96, in __init__
    self.ds_opt_adam = CPUAdamBuilder().load()
  File "/home/yunxshi/anaconda3/envs/lmflow2/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 485, in load
    return self.jit_load(verbose)
  File "/home/yunxshi/anaconda3/envs/lmflow2/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 520, in jit_load
    op_module = load(
  File "/home/yunxshi/anaconda3/envs/lmflow2/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/home/yunxshi/anaconda3/envs/lmflow2/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/yunxshi/anaconda3/envs/lmflow2/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1624, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/yunxshi/anaconda3/envs/lmflow2/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'cpu_adam'
Loading extension module cpu_adam...
Traceback (most recent call last):
  File "/data/yunxshi/workspace/LMflow/LMFlow-main/scripts/../examples/finetune.py", line 61, in <module>
    main()
  File "/data/yunxshi/workspace/LMflow/LMFlow-main/scripts/../examples/finetune.py", line 57, in main
    tuned_model = finetuner.tune(model=model, dataset=dataset)
  File "/data/yunxshi/workspace/LMflow/LMFlow-main/src/lmflow/pipeline/finetuner.py", line 274, in tune
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/yunxshi/anaconda3/envs/lmflow2/lib/python3.9/site-packages/transformers/trainer.py", line 1639, in train
    return inner_training_loop(
  File "/home/yunxshi/anaconda3/envs/lmflow2/lib/python3.9/site-packages/transformers/trainer.py", line 1708, in _inner_training_loop
    deepspeed_engine, optimizer, lr_scheduler = deepspeed_init(
  File "/home/yunxshi/anaconda3/envs/lmflow2/lib/python3.9/site-packages/transformers/deepspeed.py", line 378, in deepspeed_init
    deepspeed_engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/home/yunxshi/anaconda3/envs/lmflow2/lib/python3.9/site-packages/deepspeed/__init__.py", line 125, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/yunxshi/anaconda3/envs/lmflow2/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 340, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/yunxshi/anaconda3/envs/lmflow2/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1283, in _configure_optimizer
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/home/yunxshi/anaconda3/envs/lmflow2/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1354, in _configure_basic_optimizer
    optimizer = DeepSpeedCPUAdam(model_parameters,
  File "/home/yunxshi/anaconda3/envs/lmflow2/lib/python3.9/site-packages/deepspeed/ops/adam/cpu_adam.py", line 96, in __init__
    self.ds_opt_adam = CPUAdamBuilder().load()
  File "/home/yunxshi/anaconda3/envs/lmflow2/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 485, in load
    return self.jit_load(verbose)
  File "/home/yunxshi/anaconda3/envs/lmflow2/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 520, in jit_load
    op_module = load(
  File "/home/yunxshi/anaconda3/envs/lmflow2/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/home/yunxshi/anaconda3/envs/lmflow2/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1535, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/yunxshi/anaconda3/envs/lmflow2/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1929, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1173, in create_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ImportError: /home/yunxshi/.cache/torch_extensions/py39_cu117/cpu_adam/cpu_adam.so: cannot open shared object file: No such file or directory
Exception ignored in: <function DeepSpeedCPUAdam.__del__ at 0x2ab60f80ddc0>
Traceback (most recent call last):
  File "/home/yunxshi/anaconda3/envs/lmflow2/lib/python3.9/site-packages/deepspeed/ops/adam/cpu_adam.py", line 110, in __del__
    self.ds_opt_adam.destroy_adam(self.opt_id)
AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'
Exception ignored in: <function DeepSpeedCPUAdam.__del__ at 0x2b6665d90dc0>
Traceback (most recent call last):
  File "/home/yunxshi/anaconda3/envs/lmflow2/lib/python3.9/site-packages/deepspeed/ops/adam/cpu_adam.py", line 110, in __del__
AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'
[2023-05-07 20:16:13,074] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 119891
[2023-05-07 20:16:13,075] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 119892
[2023-05-07 20:16:13,082] [ERROR] [launch.py:324:sigkill_handler] ['/home/yunxshi/anaconda3/envs/lmflow2/bin/python', '-u', '../examples/finetune.py', '--local_rank=1', '--model_name_or_path', 'gpt2', '--dataset_path', '/home/yunxshi/Data/workspace/LMflow/LMFlow-main/data/AIducation/train', '--output_dir', '/home/yunxshi/Data/workspace/LMflow/LMFlow-main/output_models/AIducation_finetune', '--overwrite_output_dir', '--num_train_epochs', '0.01', '--learning_rate', '2e-5', '--block_size', '512', '--per_device_train_batch_size', '1', '--deepspeed', '../configs/ds_config_zero3.json', '--fp16', '--run_name', 'finetune', '--validation_split_percentage', '0', '--logging_steps', '20', '--do_train', '--ddp_timeout', '72000', '--save_steps', '5000', '--dataloader_num_workers', '1'] exits with return code = 1
```

**Comment by Ancientshi** [comment]
solved

**Comment by csyourui** [comment]
> solved

Hi, we encountered same problem, may i ask how you resolved it ?

**Comment by maxmatical** [comment]
running into the same issue with the same error message, i wonder if the issue is this part
```
FAILED: cpu_adam.so 
c++ cpu_adam.o custom_cuda_kernel.cuda.o -shared -lcurand -L/home/ec2-user/anaconda3/envs/lmflow/lib/python3.9/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda -ltorch -ltorch_python -L/home/ec2-user/anaconda3/envs/lmflow/lib64 -lcudart -o cpu_adam.so
/usr/bin/ld: cannot find -lcurand
/usr/bin/ld: cannot find -lcudart
```

**Comment by seanxuu** [comment]
> AttributeError: 'DeepSpeedCPUAdam' object has no attribute 'ds_opt_adam'

https://github.com/OptimalScale/LMFlow/issues/446#issuecomment-1576108581 
you can check my previous way.
