### ISSUE TITLE
chatglm finetune

### ISSUE THREAD

**Issue by robinchm** [OptimalScale/LMFlow#405]
**Is your feature request related to a problem? Please describe.**
Can the finetune pipeline work with chatglm?

**Describe the solution you'd like**

The model I want to finetune is 'THUDM/chatglm-6b'.

I added a few `trust_remote_code=True` to bypass transformers' custom model check, but is stopped by the following error:

```
Traceback (most recent call last):
  File "~/LMFlow/examples/finetune.py", line 61, in <module>
    main()
  File "~/LMFlow/examples/finetune.py", line 54, in main
    model = AutoModel.get_model(model_args)
  File "~/LMFlow/src/lmflow/models/auto_model.py", line 16, in get_model
    return HFDecoderModel(model_args, *args, **kwargs)
  File "~/LMFlow/src/lmflow/models/hf_decoder_model.py", line 192, in __init__
    model = AutoModelForCausalLM.from_pretrained(
  File "~/LMFlow/venv/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 470, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers_modules.THUDM.chatglm-6b.a10da4c68b5d616030d3531fc37a13bb44ea814d.configuration_chatglm.ChatGLMConfig'> for this kind of AutoModel: AutoModelForCausalLM.
Model type should be one of BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, CodeGenConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, ElectraConfig, ErnieConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, LlamaConfig, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MvpConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, TransfoXLConfig, TrOCRConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig.
```

It looks like AutoModel cannot handle the custom model with a custom config class. Is there a quick workaround to this problem? Anything quick and dirty is also fine.

**Describe alternatives you've considered**
Otherwise I'll have to use their own finetuning code which makes it hard to compare performance of different models, also not supporting lora.

**Comment by SHUMKASHUN** [comment]
Hi, 
      Chatglm finetuning is not supported by LMFlow in the current stage. It is on our feature list and we will make an announcement once it is ready. You may try finetune other enc2dec model like T5.

**Comment by robinchm** [comment]
Thanks. Will be looking out for this feature.
I'll just close this issue since it's on your roadmap already.
