### ISSUE TITLE
ModuleNotFoundError: No module named 'lmflow' Even though I didn't receive any error messages during installation.

### ISSUE THREAD

**Issue by haley05-cloud** [OptimalScale/LMFlow#423]
[2023-05-26 05:49:38,203] [INFO] [launch.py:163:main] dist_world_size=8
[2023-05-26 05:49:38,203] [INFO] [launch.py:165:main] Setting CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
Traceback (most recent call last):
  File "/home/user01/.cache1/LMFlow/examples/finetune.py", line 22, in <module>
    from lmflow.args import (
ModuleNotFoundError: No module named 'lmflow'
Traceback (most recent call last):
  File "/home/user01/.cache1/LMFlow/examples/finetune.py", line 22, in <module>
    from lmflow.args import (
ModuleNotFoundError: No module named 'lmflow'
Traceback (most recent call last):
  File "/home/user01/.cache1/LMFlow/examples/finetune.py", line 22, in <module>
    from lmflow.args import (
ModuleNotFoundError: No module named 'lmflow'
Traceback (most recent call last):
  File "/home/user01/.cache1/LMFlow/examples/finetune.py", line 22, in <module>
    from lmflow.args import (
ModuleNotFoundError: No module named 'lmflow'
Traceback (most recent call last):
  File "/home/user01/.cache1/LMFlow/examples/finetune.py", line 22, in <module>
    from lmflow.args import (
ModuleNotFoundError: No module named 'lmflow'
Traceback (most recent call last):
  File "/home/user01/.cache1/LMFlow/examples/finetune.py", line 22, in <module>
    from lmflow.args import (
ModuleNotFoundError: No module named 'lmflow'
Traceback (most recent call last):
  File "/home/user01/.cache1/LMFlow/examples/finetune.py", line 22, in <module>
    from lmflow.args import (
ModuleNotFoundError: No module named 'lmflow'
Traceback (most recent call last):
  File "/home/user01/.cache1/LMFlow/examples/finetune.py", line 22, in <module>
    from lmflow.args import (
ModuleNotFoundError: No module named 'lmflow'
[2023-05-26 05:49:39,206] [INFO] [launch.py:314:sigkill_handler] Killing subprocess 2094170
[2023-05-26 05:49:39,224] [INFO] [launch.py:314:sigkill_handler] Killing subprocess 2094171
[2023-05-26 05:49:39,239] [INFO] [launch.py:314:sigkill_handler] Killing subprocess 2094172
[2023-05-26 05:49:39,239] [INFO] [launch.py:314:sigkill_handler] Killing subprocess 2094173
[2023-05-26 05:49:39,253] [INFO] [launch.py:314:sigkill_handler] Killing subprocess 2094174
[2023-05-26 05:49:39,267] [INFO] [launch.py:314:sigkill_handler] Killing subprocess 2094175
[2023-05-26 05:49:39,280] [INFO] [launch.py:314:sigkill_handler] Killing subprocess 2094176
[2023-05-26 05:49:39,293] [INFO] [launch.py:314:sigkill_handler] Killing subprocess 2094177
[2023-05-26 05:49:39,307] [ERROR] [launch.py:320:sigkill_handler] ['/usr/bin/python3.10', '-u', 'examples/finetune.py', '--local_rank=7', '--model_name_or_path', 'gpt2', '--dataset_path', '/home/user01/.cache1/LMFlow/data/alpaca/train', '--output_dir', '/home/user01/.cache1/LMFlow/output_models/finetune', '--overwrite_output_dir', '--num_train_epochs', '0.01', '--learning_rate', '2e-5', '--block_size', '512', '--per_device_train_batch_size', '1', '--deepspeed', 'configs/ds_config_zero3.json', '--bf16', '--run_name', 'finetune', '--validation_split_percentage', '0', '--logging_steps', '20', '--do_train', '--ddp_timeout', '72000', '--save_steps', '5000', '--dataloader_num_workers', '1'] exits with return code = 1

pip list |grep lmflow
lmflow                   0.0.1
 pip3 list |grep lmflow
lmflow                   0.0.1

I have tried installing it several times, but it keeps showing this error. Could you help me figure out what the problem is?

_Originally posted by @haley05-cloud in https://github.com/OptimalScale/LMFlow/issues/305#issuecomment-1563843539_

install logs
Building wheels for collected packages: deepspeed, lm-eval, peft, transformers, trl
  Building wheel for deepspeed (setup.py) ... done
  Created wheel for deepspeed: filename=deepspeed-0.8.3-py3-none-any.whl size=776358 sha256=684ac07331537fddf4384b7cd981e4eca9b2476462098079dfd6091eb5c1a6b2
  Stored in directory: /tmp/pip-ephem-wheel-cache-583w_en0/wheels/3f/b0/60/15b10cb5fac88718fa4d189ee3118bcf52d8fa8c9bdb59e06d
  Building wheel for lm-eval (setup.py) ... done
  Created wheel for lm-eval: filename=lm_eval-0.3.0-py3-none-any.whl size=183837 sha256=c758b324d60aa8ff6f50e2ba274ec0fa7052166a3e3a1296d809069ca97c8074
  Stored in directory: /tmp/pip-ephem-wheel-cache-583w_en0/wheels/6e/3f/e4/d4571433d92ff536c7867d844a3e91f0332c4661a30f1f0dac
  Building wheel for peft (pyproject.toml) ... done
  Created wheel for peft: filename=peft-0.3.0.dev0-py3-none-any.whl size=41746 sha256=188e05d65e221993d13c11aa3dd516a66182d572ac1976190a83ba10fa88ba05
  Stored in directory: /tmp/pip-ephem-wheel-cache-583w_en0/wheels/c7/ee/de/37be9df532227b23644f110489009ee791e195bf450f38cbf9
  Building wheel for transformers (pyproject.toml) ... done
  Created wheel for transformers: filename=transformers-4.28.0.dev0-py3-none-any.whl size=6858413 sha256=c986f3edc842e675046301808ba87c287884c251a754d9109d9f95668b55d0b9
  Stored in directory: /tmp/pip-ephem-wheel-cache-583w_en0/wheels/cb/40/23/b5753f3a943d8141b2cbdaed9352b8fb411c274fb75231f98c
  Building wheel for trl (setup.py) ... done
  Created wheel for trl: filename=trl-0.4.2.dev0-py3-none-any.whl size=67601 sha256=e8e06ff62380f59ee1095bcaf80e991048d37018df34be0431a958ce8c701711
  Stored in directory: /tmp/pip-ephem-wheel-cache-583w_en0/wheels/ab/81/88/2e3ddd7591b397b560da92477ae2578b9b6f16f97a57ef49e1
Successfully built deepspeed lm-eval peft transformers trl
Installing collected packages: sentencepiece, cpm_kernels, bitsandbytes, numpy, dill, flask, wandb, transformers, scikit-learn, flask_cors, datasets, evaluate, torch, peft, trl, lm-eval, icetk, deepspeed, lmflow
  Running setup.py develop for lmflow
Successfully installed bitsandbytes-0.38.1 cpm_kernels-1.0.11 datasets-2.10.1 deepspeed-0.8.3 dill-0.3.4 evaluate-0.4.0 flask-2.3.2 flask_cors-3.0.10 icetk-0.0.7 lm-eval-0.3.0 lmflow-0.0.1 numpy-1.24.2 peft-0.3.0.dev0 scikit-learn-1.2.2 sentencepiece-0.1.99 torch-2.0.0 transformers-4.28.0.dev0 trl-0.4.2.dev0 wandb-0.14.0

**Comment by shizhediao** [comment]
there might be some issues with the python environment. Could you check your python path by `which python`? and see whether you are using the correct python path.

**Comment by haley05-cloud** [comment]
My installation steps are as follows：

conda create -n lmflow1 python=3.9 -y
conda activate lmflow1
conda install mpi4py
pip install -e .


which python
/home/user01/.anaconda3/envs/lmflow1/bin/python

/home/user01/.anaconda3/envs/lmflow1/bin/python --version
Python 3.9.16

**Comment by haley05-cloud** [comment]
> there might be some issues with the python environment. Could you check your python path by `which python`? and see whether you are using the correct python path.


conda activate lmflow1
which python
/home/user01/.anaconda3/envs/lmflow1/bin/python

/home/user01/.anaconda3/envs/lmflow1/bin/python --version
Python 3.9.16

python --version
Python 3.9.16

My installation steps are as follows:
conda create -n lmflow1 python=3.9 -y
conda activate lmflow1
conda install mpi4py
pip install -e .

**Comment by haley05-cloud** [comment]
> 
I'm sorry.
You can ignore my question. It is due to the system configuration that PATH defaults to searching for the deepspeed binary under .local/bin, instead of using the deepspeed installed in the conda virtual environment.

**Comment by shizhediao** [comment]
Hi,
Nice to hear that.
