### ISSUE TITLE
test_hf_decoder_model.py  failed

### ISSUE THREAD

**Issue by tanis2010** [OptimalScale/LMFlow#44]
error message is as follow:
`Error
Traceback (most recent call last):
  File "/home/lidong/git/LMFlow/tests/models/test_hf_decoder_model.py", line 100, in test_inference
    outputs = model.inference(inputs,min_length=5, max_length=100,temperature=0.0, do_sample=False)
  File "/home/lidong/git/LMFlow/src/lmflow/models/hf_decoder_model.py", line 350, in inference
    outputs = self.ds_engine.module.generate(
  File "/home/lidong/anaconda3/envs/lmflow/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/lidong/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/generation/utils.py", line 1406, in generate
    return self.greedy_search(
  File "/home/lidong/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/generation/utils.py", line 2201, in greedy_search
    outputs = self(
  File "/home/lidong/anaconda3/envs/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/lidong/anaconda3/envs/lmflow/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/lidong/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 1075, in forward
    transformer_outputs = self.transformer(
  File "/home/lidong/anaconda3/envs/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/lidong/anaconda3/envs/lmflow/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/lidong/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 899, in forward
    outputs = block(
  File "/home/lidong/anaconda3/envs/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/lidong/anaconda3/envs/lmflow/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/lidong/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 389, in forward
    attn_outputs = self.attn(
  File "/home/lidong/anaconda3/envs/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/lidong/anaconda3/envs/lmflow/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/lidong/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 311, in forward
    query, key, value = self.c_attn(hidden_states).split(self.split_size, dim=2)
  File "/home/lidong/anaconda3/envs/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/lidong/anaconda3/envs/lmflow/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/lidong/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/pytorch_utils.py", line 114, in forward
    x = torch.addmm(self.bias, x.view(-1, x.size(-1)), self.weight)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

Ran 1 test in 16.964s

FAILED (errors=1)

Process finished with exit code 1`

**Comment by research4pan** [comment]
Thanks for your feedback! This can be caused by the memory-optimized offload during model loading. We've fixed this bug in our latest main branch. Could you please try to update the code and check if the issue is fixed? Thanks very much! 😄 
```
git pull origin main
pip install -e .
...
```
