### ISSUE TITLE
[BUG] An error occurred in config.py: root_validator() takes 0 positional arguments but 1 was given

### ISSUE THREAD

**Issue by halipotezzz32** [OptimalScale/LMFlow#444]
**Describe the bug**
Currently I am dealing with an error occurred when running the command `./scripts/run_finetune.sh` and it shows `TypeError: root_validator() takes 0 positional arguments but 1 was given`.
Seemingly this error comes from the function `get_monitor_config` in `./deepspeed-0.8.3-py3.9.egg/deepspeed/monitor/config.py` file and it works as a verification check to valify the key-value pair. However, I can't understand why there's 1 extra argument.

Actually I encounter another problem, which I don't know whether it's related to this error:
Due to the network connection, I ran `python setup.py install` instead of `pip install -e .` to deploy lmflow. In the requirement.txt, `dill<0.3.5` is installed but `dill>=0.3.6` is required for {'multiprocess'} (I think it derives from the package `multiprocessing` ). 
Since I don't know how to fix it, I simply modify the `requirement.txt` and switch the denpendency to `dill=0.3.6`. Does it matter?

**To Reproduce**
1. Download and bash 'download.sh'
2. Run `./scripts/run_finetune.sh`
3. See error `./deepspeed-0.8.3-py3.9.egg/deepspeed/monitor/config.py`.

This is the full codes:
```# ./scripts/run_finetune.sh
/JCH/anaconda3/envs/lmflow_jch/lib/python3.9/site-packages/pydantic-2.0a4-py3.9.egg/pydantic/_internal/_config.py:233: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
* 'validate_all' has been renamed to 'validate_default'
  warnings.warn(message, UserWarning)
/JCH/anaconda3/envs/lmflow_jch/lib/python3.9/site-packages/pydantic-2.0a4-py3.9.egg/pydantic/_internal/_config.py:233: UserWarning: Valid config keys have changed in V2:
* 'validate_all' has been renamed to 'validate_default'
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "/JCH/anaconda3/envs/lmflow_jch/bin/deepspeed", line 4, in <module>
    __import__('pkg_resources').run_script('deepspeed==0.8.3', 'deepspeed')
  File "/JCH/anaconda3/envs/lmflow_jch/lib/python3.9/site-packages/pkg_resources/__init__.py", line 720, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/JCH/anaconda3/envs/lmflow_jch/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1559, in run_script
    exec(code, namespace, namespace)
  File "/JCH/anaconda3/envs/lmflow_jch/lib/python3.9/site-packages/deepspeed-0.8.3-py3.9.egg/EGG-INFO/scripts/deepspeed", line 3, in <module>
    from deepspeed.launcher.runner import main
  File "/JCH/anaconda3/envs/lmflow_jch/lib/python3.9/site-packages/deepspeed-0.8.3-py3.9.egg/deepspeed/__init__.py", line 15, in <module>
    from . import module_inject
  File "/JCH/anaconda3/envs/lmflow_jch/lib/python3.9/site-packages/deepspeed-0.8.3-py3.9.egg/deepspeed/module_inject/__init__.py", line 3, in <module>
    from .replace_module import replace_transformer_layer, revert_transformer_layer, ReplaceWithTensorSlicing, GroupQuantizer, generic_injection
  File "/JCH/anaconda3/envs/lmflow_jch/lib/python3.9/site-packages/deepspeed-0.8.3-py3.9.egg/deepspeed/module_inject/replace_module.py", line 803, in <module>
    from ..pipe import PipelineModule
  File "/JCH/anaconda3/envs/lmflow_jch/lib/python3.9/site-packages/deepspeed-0.8.3-py3.9.egg/deepspeed/pipe/__init__.py", line 3, in <module>
    from ..runtime.pipe import PipelineModule, LayerSpec, TiedLayerSpec
  File "/JCH/anaconda3/envs/lmflow_jch/lib/python3.9/site-packages/deepspeed-0.8.3-py3.9.egg/deepspeed/runtime/pipe/__init__.py", line 3, in <module>
    from .module import PipelineModule, LayerSpec, TiedLayerSpec
  File "/JCH/anaconda3/envs/lmflow_jch/lib/python3.9/site-packages/deepspeed-0.8.3-py3.9.egg/deepspeed/runtime/pipe/module.py", line 16, in <module>
    from ..activation_checkpointing import checkpointing
  File "/JCH/anaconda3/envs/lmflow_jch/lib/python3.9/site-packages/deepspeed-0.8.3-py3.9.egg/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 25, in <module>
    from deepspeed.runtime.config import DeepSpeedConfig
  File "/JCH/anaconda3/envs/lmflow_jch/lib/python3.9/site-packages/deepspeed-0.8.3-py3.9.egg/deepspeed/runtime/config.py", line 30, in <module>
    from ..monitor.config import get_monitor_config
  File "/JCH/anaconda3/envs/lmflow_jch/lib/python3.9/site-packages/deepspeed-0.8.3-py3.9.egg/deepspeed/monitor/config.py", line 72, in <module>
    class DeepSpeedMonitorConfig(DeepSpeedConfigModel):
  File "/JCH/anaconda3/envs/lmflow_jch/lib/python3.9/site-packages/deepspeed-0.8.3-py3.9.egg/deepspeed/monitor/config.py", line 85, in DeepSpeedMonitorConfig
    def check_enabled(cls, values):
TypeError: root_validator() takes 0 positional arguments but 1 was given
```

**Comment by halipotezzz32** [comment]
After I annotate the decorator `# @root_validator`, here comes a new error:

```
/JCH/anaconda3/envs/lmflow_jch/lib/python3.9/site-packages/pydantic-2.0a4-py3.9.egg/pydantic/_internal/_config.py:233: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
* 'validate_all' has been renamed to 'validate_default'
  warnings.warn(message, UserWarning)
/JCH/anaconda3/envs/lmflow_jch/lib/python3.9/site-packages/pydantic-2.0a4-py3.9.egg/pydantic/_internal/_config.py:233: UserWarning: Valid config keys have changed in V2:
* 'validate_all' has been renamed to 'validate_default'
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "/JCH/anaconda3/envs/lmflow_jch/bin/deepspeed", line 4, in <module>
    __import__('pkg_resources').run_script('deepspeed==0.8.3', 'deepspeed')
  File "/JCH/anaconda3/envs/lmflow_jch/lib/python3.9/site-packages/pkg_resources/__init__.py", line 720, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/JCH/anaconda3/envs/lmflow_jch/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1559, in run_script
    exec(code, namespace, namespace)
  File "/JCH/anaconda3/envs/lmflow_jch/lib/python3.9/site-packages/deepspeed-0.8.3-py3.9.egg/EGG-INFO/scripts/deepspeed", line 3, in <module>
    from deepspeed.launcher.runner import main
  File "/JCH/anaconda3/envs/lmflow_jch/lib/python3.9/site-packages/deepspeed-0.8.3-py3.9.egg/deepspeed/__init__.py", line 17, in <module>
    from .runtime.engine import DeepSpeedEngine, DeepSpeedOptimizerCallable, DeepSpeedSchedulerCallable
  File "/JCH/anaconda3/envs/lmflow_jch/lib/python3.9/site-packages/deepspeed-0.8.3-py3.9.egg/deepspeed/runtime/engine.py", line 95, in <module>
    from deepspeed.inference.config import DtypeEnum
  File "/JCH/anaconda3/envs/lmflow_jch/lib/python3.9/site-packages/deepspeed-0.8.3-py3.9.egg/deepspeed/inference/config.py", line 90, in <module>
    class BaseQuantConfig(DeepSpeedConfigModel):
  File "/JCH/anaconda3/envs/lmflow_jch/lib/python3.9/site-packages/pydantic-2.0a4-py3.9.egg/pydantic/main.py", line 96, in __new__
    private_attributes = _model_construction.inspect_namespace(
  File "/JCH/anaconda3/envs/lmflow_jch/lib/python3.9/site-packages/pydantic-2.0a4-py3.9.egg/pydantic/_internal/_model_construction.py", line 121, in inspect_namespace
    raise PydanticUserError(
pydantic.errors.PydanticUserError: A non-annotated attribute was detected: `enabled = True`. All model fields require a type annotation; if `enabled` is not meant to be a field, you may be able to resolve this error by annotating it as a `ClassVar` or updating `model_config['ignored_types']`.

For further information visit https://errors.pydantic.dev/2.0a4/u/model-field-missing-annotation
```

**Comment by research4pan** [comment]
Thanks for your interest in LMFlow! Seems like a dependency problem, as the error is raised during importing of the deepspeed package. Could you please run `pip list` so we may check if all necessary packages are installed? Also, it would be nice if you could provide the CUDA version, nvcc version and other possibly relevant environment statisitcs, so we may check that for you? Thanks 😄

**Comment by halipotezzz32** [comment]
> 

Thank you for replying. This is my `pip list` package:
```
Package                  Version
------------------------ ------------------

- absl-py                  1.4.0
- accelerate               0.19.0
- aiohttp                  3.8.4
- aiosignal                1.3.1
- annotated-types          0.5.0
- antlr4-python3-runtime   4.9.3
- appdirs                  1.4.4
- async-timeout            4.0.2
- attrs                    23.1.0
- blinker                  1.6.2
- brotlipy                 0.7.0
- certifi                  2023.5.7
- cffi                     1.15.1
- chardet                  3.0.4
- charset-normalizer       2.0.4
- click                    8.0.4
- cmake                    3.26.3
- colorama                 0.4.6
- cpm-kernels              1.0.11
- cryptography             39.0.1
- DataProperty             0.55.1
- datasets                 2.10.1
- deepspeed                0.8.3
- dill                     0.3.6
- docker-pycreds           0.4.0
- evaluate                 0.4.0
- filelock                 3.9.0
- Flask                    2.3.2
- Flask-Cors               3.0.10
- frozenlist               1.3.3
- fsspec                   2023.5.0
- gitdb                    4.0.10
- GitPython                3.1.31
- gmpy2                    2.1.2
- hjson                    3.1.0
- huggingface-hub          0.14.1
- icetk                    0.0.7
- idna                     3.4
- importlib-metadata       6.0.0
- itsdangerous             2.1.2
- Jinja2                   3.1.2
- joblib                   1.1.1
- jsonlines                3.1.0
- lit                      16.0.5
- llvmlite                 0.40.0
- lm-eval                  0.3.0
- lmflow                   0.0.1
- MarkupSafe               2.1.2
- mbstrdecoder             1.1.2
- mkl-fft                  1.3.6
- mkl-random               1.2.2
- mkl-service              2.4.0
- mpi4py                   3.1.4
- mpmath                   1.3.0
- multidict                4.7.6
- multiprocess             0.70.14
- networkx                 3.1
- ninja                    1.11.1
- nltk                     3.8.1
- numba                    0.57.0
- numexpr                  2.8.4
- numpy                    1.24.3
- nvidia-cublas-cu11       11.10.3.66
- nvidia-cuda-cupti-cu11   11.7.101
- nvidia-cuda-nvrtc-cu11   11.7.99
- nvidia-cuda-runtime-cu11 11.7.99
- nvidia-cudnn-cu11        8.5.0.96
- nvidia-cufft-cu11        10.9.0.58
- nvidia-curand-cu11       10.2.10.91
- nvidia-cusolver-cu11     11.4.0.1
- nvidia-cusparse-cu11     11.7.4.91
- nvidia-nccl-cu11         2.14.3
- nvidia-nvtx-cu11         11.7.91
- omegaconf                2.3.0
- openai                   0.27.7
- packaging                23.0
- pandas                   2.0.2
- pathtools                0.1.2
- pathvalidate             2.5.2
- peft                     0.3.0
- Pillow                   9.4.0
- pip                      23.1.2
- portalocker              2.7.0
- protobuf                 3.20.3
- psutil                   5.9.5
- py-cpuinfo               9.0.0
- pyarrow                  12.0.0
- pybind11                 2.10.4
- pycountry                22.3.5
- pycparser                2.21
- pydantic                 2.0a4
- pydantic_core            0.30.0
- pyOpenSSL                23.0.0
- PySocks                  1.7.1
- pytablewriter            0.64.2
- python-dateutil          2.8.2
- pytz                     2023.3
- PyYAML                   6.0
- regex                    2022.7.9
- requests                 2.29.0
- responses                0.18.0
- rouge-score              0.1.2
- sacrebleu                1.5.0
- sacremoses               0.0.43
- scikit-learn             1.2.2
- scipy                    1.10.1
- sentencepiece            0.1.99
- sentry-sdk               1.24.0
- setproctitle             1.3.2
- setuptools               67.8.0
- six                      1.16.0
- smmap                    5.0.0
- sqlitedict               2.1.0
- sympy                    1.12
- tabledata                1.3.1
- tcolorpy                 0.1.3
- threadpoolctl            3.1.0
- tokenizers               0.13.0.dev0
- torch                    2.0.1
- torchaudio               2.1.0.dev20230529
- torchvision              0.16.0.dev20230529
- tqdm                     4.65.0
- tqdm-multiprocess        0.0.11
- transformers             4.28.1
- triton                   2.0.0
- trl                      0.4.1
- typepy                   1.3.0
- typing_extensions        4.5.0
- tzdata                   2023.3
- urllib3                  1.26.15
- wandb                    0.14.0
- Werkzeug                 2.3.4
- wheel                    0.40.0
- xxhash                   3.2.0
- yarl                     1.9.2
- zipp                     3.11.0
- zstandard                0.21.0

```
and this is the output of the cmd `nvcc -V`:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0
```
Any else necessary to be provided? I'm not so sure whether `conda list` is needed (the output is too long) since I installed some packages using Anaconda, so I paste it at the end:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
absl-py                   1.4.0                    pypi_0    pypi
accelerate                0.19.0                   pypi_0    pypi
aiohttp                   3.8.4                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
annotated-types           0.5.0                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
blas                      1.0                         mkl  
blinker                   1.6.2                    pypi_0    pypi
brotlipy                  0.7.0           py39h27cfd23_1003  
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.19.0               h5eee18b_0  
ca-certificates           2023.01.10           h06a4308_0  
certifi                   2023.5.7         py39h06a4308_0  
cffi                      1.15.1           py39h5eee18b_3  
chardet                   3.0.4                    pypi_0    pypi
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.1.3                    pypi_0    pypi
cmake                     3.26.3                   pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
cpm-kernels               1.0.11                   pypi_0    pypi
cryptography              39.0.1           py39h9ce1e76_0  
cuda-cudart               12.1.105                      0    nvidia
cuda-cupti                12.1.105                      0    nvidia
cuda-libraries            12.1.0                        0    nvidia
cuda-nvrtc                12.1.105                      0    nvidia
cuda-nvtx                 12.1.105                      0    nvidia
cuda-opencl               12.1.105                      0    nvidia
cuda-runtime              12.1.0                        0    nvidia
cudatoolkit               11.8.0               h6a678d5_0  
curl                      7.88.1               h5eee18b_0  
dataclasses               0.8                pyh6d0b6a4_7  
dataproperty              0.55.1                   pypi_0    pypi
datasets                  2.10.1                   pypi_0    pypi
deepspeed                 0.8.3                    pypi_0    pypi
dill                      0.3.6                    pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
evaluate                  0.4.0                    pypi_0    pypi
expat                     2.4.9                h6a678d5_0  
ffmpeg                    4.2.2                h20bf706_0  
filelock                  3.9.0            py39h06a4308_0  
flask                     2.3.2                    pypi_0    pypi
flask-cors                3.0.10                   pypi_0    pypi
freetype                  2.12.1               h4a9f257_0  
frozenlist                1.3.3                    pypi_0    pypi
fsspec                    2023.5.0                 pypi_0    pypi
gdbm                      1.18                 hd4cb3f1_4  
gettext                   0.21.0               h39681ba_1  
giflib                    5.2.1                h5eee18b_3  
git                       2.34.1          pl5262hc120c5b_0  
gitdb                     4.0.10                   pypi_0    pypi
gitpython                 3.1.31                   pypi_0    pypi
gmp                       6.2.1                h295c915_3  
gmpy2                     2.1.2            py39heeb90bb_0  
gnutls                    3.6.15               he1e5248_0  
hjson                     3.1.0                    pypi_0    pypi
huggingface-hub           0.14.1                   pypi_0    pypi
huggingface_hub           0.14.1                     py_0    huggingface
icetk                     0.0.7                    pypi_0    pypi
icu                       58.2                 he6710b0_3  
idna                      3.4              py39h06a4308_0  
importlib-metadata        6.0.0            py39h06a4308_0  
importlib_metadata        6.0.0                hd3eb1b0_0  
intel-openmp              2023.1.0         hdb19cb5_46305  
itsdangerous              2.1.2                    pypi_0    pypi
jinja2                    3.1.2            py39h06a4308_0  
joblib                    1.1.1            py39h06a4308_0  
jpeg                      9e                   h5eee18b_1  
jsonlines                 3.1.0                    pypi_0    pypi
krb5                      1.19.4               h568e23c_0  
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      3.0                  h295c915_0  
libcublas                 12.1.0.26                     0    nvidia
libcufft                  11.0.2.4                      0    nvidia
libcufile                 1.6.1.9                       0    nvidia
libcurand                 10.3.2.106                    0    nvidia
libcurl                   7.88.1               h91b91d3_0  
libcusolver               11.4.4.55                     0    nvidia
libcusparse               12.0.2.55                     0    nvidia
libdeflate                1.17                 h5eee18b_0  
libedit                   3.1.20221030         h5eee18b_0  
libev                     4.33                 h7f8727e_1  
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 11.2.0               h1234567_1  
libgfortran-ng            7.5.0               ha8ba4b0_17  
libgfortran4              7.5.0               ha8ba4b0_17  
libgomp                   11.2.0               h1234567_1  
libidn2                   2.3.4                h5eee18b_0  
libllvm14                 14.0.6               hdb19cb5_3  
libnghttp2                1.46.0               hce63b2e_0  
libnpp                    12.0.2.50                     0    nvidia
libnvjitlink              12.1.105                      0    nvidia
libnvjpeg                 12.1.0.39                     0    nvidia
libopus                   1.3.1                h7b6447c_0  
libpng                    1.6.39               h5eee18b_0  
libprotobuf               3.20.3               he621ea3_0  
libssh2                   1.10.0               h8f2d780_0  
libstdcxx-ng              11.2.0               h1234567_1  
libtasn1                  4.19.0               h5eee18b_0  
libtiff                   4.5.0                h6a678d5_2  
libunistring              0.9.10               h27cfd23_0  
libvpx                    1.7.0                h439df22_0  
libwebp                   1.2.4                h11a3e52_1  
libwebp-base              1.2.4                h5eee18b_1  
libxml2                   2.10.3               hcbfbd50_0  
lit                       16.0.5                   pypi_0    pypi
llvmlite                  0.40.0           py39he621ea3_0  
lm-eval                   0.3.0                    pypi_0    pypi
lmflow                    0.0.1                    pypi_0    pypi
lz4-c                     1.9.4                h6a678d5_0  
markupsafe                2.1.2                    pypi_0    pypi
mbstrdecoder              1.1.2                    pypi_0    pypi
mkl                       2023.1.0         h6d00ec8_46342  
mkl-service               2.4.0            py39h5eee18b_1  
mkl_fft                   1.3.6            py39h417a72b_1  
mkl_random                1.2.2            py39h417a72b_1  
mpc                       1.1.0                h10f8cd9_1  
mpfr                      4.0.2                hb69a4c5_1  
mpi                       1.0                       mpich  
mpi4py                    3.1.4            py39hfc96bbd_0  
mpich                     3.3.2                hc856adb_0  
mpmath                    1.3.0                    pypi_0    pypi
multidict                 4.7.6                    pypi_0    pypi
multiprocess              0.70.14                  pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
nettle                    3.7.3                hbbd107a_1  
networkx                  3.1                      pypi_0    pypi
ninja                     1.11.1                   pypi_0    pypi
nltk                      3.8.1                    pypi_0    pypi
numba                     0.57.0           py39h1128e8f_0  
numexpr                   2.8.4                    pypi_0    pypi
numpy                     1.24.2                   pypi_0    pypi
numpy-base                1.24.3           py39h060ed82_1  
nvidia-cublas-cu11        11.10.3.66               pypi_0    pypi
nvidia-cuda-cupti-cu11    11.7.101                 pypi_0    pypi
nvidia-cuda-nvrtc-cu11    11.7.99                  pypi_0    pypi
nvidia-cuda-runtime-cu11  11.7.99                  pypi_0    pypi
nvidia-cudnn-cu11         8.5.0.96                 pypi_0    pypi
nvidia-cufft-cu11         10.9.0.58                pypi_0    pypi
nvidia-curand-cu11        10.2.10.91               pypi_0    pypi
nvidia-cusolver-cu11      11.4.0.1                 pypi_0    pypi
nvidia-cusparse-cu11      11.7.4.91                pypi_0    pypi
nvidia-nccl-cu11          2.14.3                   pypi_0    pypi
nvidia-nvtx-cu11          11.7.91                  pypi_0    pypi
omegaconf                 2.3.0                    pypi_0    pypi
openai                    0.27.7                   pypi_0    pypi
openh264                  2.1.1                h4ff587b_0  
openssl                   1.1.1t               h7f8727e_0  
packaging                 23.0             py39h06a4308_0  
pandas                    2.0.2                    pypi_0    pypi
pathvalidate              2.5.2                    pypi_0    pypi
pcre2                     10.37                he7ceb23_1  
peft                      0.3.0                    pypi_0    pypi
perl                      5.34.0               h5eee18b_2  
pillow                    9.4.0            py39h6a678d5_0  
pip                       23.1.2                   pypi_0    pypi
portalocker               2.7.0                    pypi_0    pypi
protobuf                  3.18.3                   pypi_0    pypi
psutil                    5.9.5                    pypi_0    pypi
py-cpuinfo                9.0.0                    pypi_0    pypi
pyarrow                   12.0.0                   pypi_0    pypi
pybind11                  2.10.4                   pypi_0    pypi
pycountry                 22.3.5                   pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0  
pydantic                  2.0a4                    pypi_0    pypi
pydantic-core             0.30.0                   pypi_0    pypi
pyopenssl                 23.0.0           py39h06a4308_0  
pysocks                   1.7.1            py39h06a4308_0  
pytablewriter             0.64.2                   pypi_0    pypi
python                    3.9.16               h7a1cb2a_2  
python-dateutil           2.8.2                    pypi_0    pypi
pytorch-cuda              12.1                 ha16c6d3_5    pytorch-nightly
pytorch-mutex             1.0                        cuda    pytorch-nightly
pytz                      2023.3                   pypi_0    pypi
pyyaml                    6.0              py39h5eee18b_1  
readline                  8.2                  h5eee18b_0  
regex                     2022.7.9         py39h5eee18b_0  
requests                  2.29.0           py39h06a4308_0  
responses                 0.18.0                   pypi_0    pypi
rouge-score               0.1.2                    pypi_0    pypi
sacrebleu                 1.5.0                    pypi_0    pypi
sacremoses                master                     py_0    huggingface
scikit-learn              1.2.2                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
sentencepiece             0.1.99                   pypi_0    pypi
sentry-sdk                1.24.0                   pypi_0    pypi
setproctitle              1.3.2                    pypi_0    pypi
setuptools                67.7.2                   pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_1  
smmap                     5.0.0                    pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0  
sympy                     1.12                     pypi_0    pypi
tabledata                 1.3.1                    pypi_0    pypi
tbb                       2021.8.0             hdb19cb5_0  
tcolorpy                  0.1.3                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
tokenizers                0.13.0.dev0              py39_0    huggingface
torch                     2.0.1                    pypi_0    pypi
torchaudio                2.1.0.dev20230529      py39_cu121    pytorch-nightly
torchvision               0.16.0.dev20230529      py39_cu121    pytorch-nightly
tqdm                      4.65.0           py39hb070fc8_0  
tqdm-multiprocess         0.0.11                   pypi_0    pypi
transformers              4.29.2                   pypi_0    pypi
triton                    2.0.0                    pypi_0    pypi
trl                       0.4.1                    pypi_0    pypi
typepy                    1.3.0                    pypi_0    pypi
typing-extensions         4.5.0            py39h06a4308_0  
typing_extensions         4.5.0            py39h06a4308_0  
tzdata                    2023.3                   pypi_0    pypi
urllib3                   1.26.15          py39h06a4308_0  
wandb                     0.14.0                   pypi_0    pypi
werkzeug                  2.3.4                    pypi_0    pypi
wheel                     0.40.0                   pypi_0    pypi
x264                      1!157.20191217       h7b6447c_0  
xxhash                    3.2.0                    pypi_0    pypi
xz                        5.4.2                h5eee18b_0  
yaml                      0.2.5                h7b6447c_0  
yarl                      1.9.2                    pypi_0    pypi
zipp                      3.11.0           py39h06a4308_0  
zlib                      1.2.13               h5eee18b_0  
zstandard                 0.21.0                   pypi_0    pypi
zstd                      1.5.5                hc292b87_0 
```

**Comment by shizhediao** [comment]
Hi,
What is the exact problem with `monitor.py`? If it is an issue of deepspeed, you may create an issue in deepspeed repo and seek their help.

**Comment by halipotezzz32** [comment]
Thank you for replying!
I think it derives from an inconsistency between the version of CUDA and torch. See issue microsoft/DeepSpeed#2902.

**Comment by shizhediao** [comment]
ok thanks!
