### ISSUE TITLE
[BUG]Using chatbot.py to deploy robin-7b-v2-delta，occured NotImplementedError: Cannot copy out of meta tensor; no data!

### ISSUE THREAD

**Issue by snake-head** [OptimalScale/LMFlow#451]
**Describe the bug**
Using chatbot.py to deploy robin-7b-v2-delta，occured NotImplementedError: Cannot copy out of meta tensor; no data!

**To Reproduce**
./scripts/run_chatbot.sh output_models/robin-7b-v2-delta/

**Error Msg**
(lmflow) root@cuda:/opt/LMFlow# ./scripts/run_chatbot.sh output_models/robin-7b-v2-delta/
[2023-06-02 04:55:12,018] [WARNING] [runner.py:186:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
Detected CUDA_VISIBLE_DEVICES=0: setting --include=localhost:0
[2023-06-02 04:55:12,060] [INFO] [runner.py:550:main] cmd = /root/miniconda3/envs/lmflow/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None examples/chatbot.py --deepspeed configs/ds_config_chatbot.json --model_name_or_path output_models/robin-7b-v2-delta/
[2023-06-02 04:55:14,724] [INFO] [launch.py:135:main] 0 NV_LIBNCCL_DEV_PACKAGE=libnccl-dev=2.9.6-1+cuda11.3
[2023-06-02 04:55:14,724] [INFO] [launch.py:135:main] 0 NV_LIBNCCL_DEV_PACKAGE_VERSION=2.9.6-1
[2023-06-02 04:55:14,724] [INFO] [launch.py:135:main] 0 NCCL_VERSION=2.9.6-1
[2023-06-02 04:55:14,724] [INFO] [launch.py:135:main] 0 NV_LIBNCCL_DEV_PACKAGE_NAME=libnccl-dev
[2023-06-02 04:55:14,724] [INFO] [launch.py:135:main] 0 NV_LIBNCCL_PACKAGE=libnccl2=2.9.6-1+cuda11.3
[2023-06-02 04:55:14,724] [INFO] [launch.py:135:main] 0 NV_LIBNCCL_PACKAGE_NAME=libnccl2
[2023-06-02 04:55:14,724] [INFO] [launch.py:135:main] 0 NV_LIBNCCL_PACKAGE_VERSION=2.9.6-1
[2023-06-02 04:55:14,724] [INFO] [launch.py:142:main] WORLD INFO DICT: {'localhost': [0]}
[2023-06-02 04:55:14,724] [INFO] [launch.py:148:main] nnodes=1, num_local_procs=1, node_rank=0
[2023-06-02 04:55:14,724] [INFO] [launch.py:161:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2023-06-02 04:55:14,724] [INFO] [launch.py:162:main] dist_world_size=1
[2023-06-02 04:55:14,724] [INFO] [launch.py:164:main] Setting CUDA_VISIBLE_DEVICES=0

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /root/miniconda3/envs/lmflow/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda113.so
/root/miniconda3/envs/lmflow/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: /root/miniconda3/envs/lmflow did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 113
CUDA SETUP: Loading binary /root/miniconda3/envs/lmflow/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda113.so...
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████| 2/2 [00:41<00:00, 20.51s/it]
Traceback (most recent call last):
  File "/opt/LMFlow/examples/chatbot.py", line 161, in <module>
    main()
  File "/opt/LMFlow/examples/chatbot.py", line 71, in main
    model = AutoModel.get_model(
  File "/opt/LMFlow/src/lmflow/models/auto_model.py", line 16, in get_model
    return HFDecoderModel(model_args, *args, **kwargs)
  File "/opt/LMFlow/src/lmflow/models/hf_decoder_model.py", line 306, in __init__
    self.ds_engine = deepspeed.initialize(model=self.backend_model, config_params=ds_config)[0]
  File "/root/miniconda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/__init__.py", line 125, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/root/miniconda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 297, in __init__
    self._configure_distributed_model(model)
  File "/root/miniconda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1146, in _configure_distributed_model
    self.module.to(self.device)
  File "/root/miniconda3/envs/lmflow/lib/python3.9/site-packages/transformers/modeling_utils.py", line 1861, in to
    return super().to(*args, **kwargs)
  File "/root/miniconda3/envs/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/root/miniconda3/envs/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/root/miniconda3/envs/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/root/miniconda3/envs/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/root/miniconda3/envs/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/root/miniconda3/envs/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!
[2023-06-02 04:56:19,840] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 2694
[2023-06-02 04:56:19,841] [ERROR] [launch.py:324:sigkill_handler] ['/root/miniconda3/envs/lmflow/bin/python', '-u', 'examples/chatbot.py', '--local_rank=0', '--deepspeed', 'configs/ds_config_chatbot.json', '--model_name_or_path', 'output_models/robin-7b-v2-delta/'] exits with return code = 1

**Comment by research4pan** [comment]
Thanks for your interest in LMFlow! It is highly probably that the problem was caused by RAM optimize offloading. You may refer to the [solution of this issue](https://github.com/OptimalScale/LMFlow/issues/154#issuecomment-1499430590).

Also, robin-7b-v2-delta is a model diff instead of model itself. To obtain the full model, you may use the merge script provided in [this section](https://github.com/OptimalScale/LMFlow#53-reproduce-the-result). Hope that can solve your problem. Thanks 😄

**Comment by snake-head** [comment]
This method has been really helpful. Thanks!
