### ISSUE TITLE
error message as follow

### ISSUE THREAD

**Issue by lancescrazy** [OptimalScale/LMFlow#49]
run:

CUDA_VISIBLE_DEVICES=1     deepspeed examples/evaluate.py     --answer_type text     --model_name_or_path llama-hf-path/llama-7b-hf     --lora_model_path output_models/llama7b-lora-380k     --test_file data/alpaca/test/test_252.json     --deepspeed examples/ds_config.json

error message as follow:

Traceback (most recent call last):
  File "/data/zhanghanyi/LMFlow/examples/evaluate.py", line 34, in <module>
    model = AutoModel.get_model(model_args, tune_strategy='none', ds_config=ds_config)
  File "/data/zhanghanyi/LMFlow/src/lmflow/models/auto_model.py", line 14, in get_model
    return HFDecoderModel(model_args, *args, **kwargs)
  File "/data/zhanghanyi/LMFlow/src/lmflow/models/hf_decoder_model.py", line 197, in __init__
    self.ds_engine = deepspeed.initialize(model=self.backend_model, config_params=ds_config)[0]
  File "/home/deepwisdom/anaconda3/envs/zhy_lmflow/lib/python3.9/site-packages/deepspeed/__init__.py", line 125, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/deepwisdom/anaconda3/envs/zhy_lmflow/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 297, in __init__
    self._configure_distributed_model(model)
  File "/home/deepwisdom/anaconda3/envs/zhy_lmflow/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1146, in _configure_distributed_model
    self.module.to(self.device)
  File "/home/deepwisdom/anaconda3/envs/zhy_lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/home/deepwisdom/anaconda3/envs/zhy_lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/deepwisdom/anaconda3/envs/zhy_lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/deepwisdom/anaconda3/envs/zhy_lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 5 more times]
  File "/home/deepwisdom/anaconda3/envs/zhy_lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/home/deepwisdom/anaconda3/envs/zhy_lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!

**Comment by research4pan** [comment]
Thanks for your feedback! This can be caused by the memory-optimized offload during model loading. We've fixed this bug in our latest main branch. Could you please try to update the code and check if the issue is fixed? Thanks very much! 😄 
```
git pull origin main
pip install -e .
...
```

**Comment by Alan-Qin** [comment]
After updating LMFlow to the newest version, we still have this issue when using Llama models. 

Following your suggestion, we could add --use_ram_optimized_load False in our bash file.

**Comment by PhoebeChen123** [comment]
> 

Have you solved this issue currently?

**Comment by Alan-Qin** [comment]
Yes ^_^

**Comment by research4pan** [comment]
This issue has been marked as stale because it has not had recent activity. If you think this still needs to be addressed please feel free to reopen this issue. Thanks 😄
