### ISSUE TITLE
sh run_finetune.sh error NameError: Field "model_persistence_threshold" has conflict with protected namespace "model_"NameError: Field "model_persistence_threshold" has conflict with protected namespace "model_"

### ISSUE THREAD

**Issue by alphanlp** [OptimalScale/LMFlow#539]
/data/llmodel/miniconda3/envs/lmflow/lib/python3.9/site-packages/pydantic/_internal/_config.py:257: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
* 'validate_all' has been renamed to 'validate_default'
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "/data/llmodel/miniconda3/envs/lmflow/bin/deepspeed", line 3, in <module>
    from deepspeed.launcher.runner import main
  File "/data/llmodel/miniconda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/__init__.py", line 15, in <module>
    from . import module_inject
  File "/data/llmodel/miniconda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/module_inject/__init__.py", line 3, in <module>
    from .replace_module import replace_transformer_layer, revert_transformer_layer, ReplaceWithTensorSlicing, GroupQuantizer, generic_injection
  File "/data/llmodel/miniconda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/module_inject/replace_module.py", line 803, in <module>
    from ..pipe import PipelineModule
  File "/data/llmodel/miniconda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/pipe/__init__.py", line 3, in <module>
    from ..runtime.pipe import PipelineModule, LayerSpec, TiedLayerSpec
  File "/data/llmodel/miniconda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/runtime/pipe/__init__.py", line 3, in <module>
    from .module import PipelineModule, LayerSpec, TiedLayerSpec
  File "/data/llmodel/miniconda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/runtime/pipe/module.py", line 16, in <module>
    from ..activation_checkpointing import checkpointing
  File "/data/llmodel/miniconda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 25, in <module>
    from deepspeed.runtime.config import DeepSpeedConfig
  File "/data/llmodel/miniconda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/runtime/config.py", line 27, in <module>
    from .zero.config import get_zero_config, ZeroStageEnum
  File "/data/llmodel/miniconda3/envs/lmflow/lib/python3.9/site-packages/deepspeed/runtime/zero/config.py", line 79, in <module>
    class DeepSpeedZeroConfig(DeepSpeedConfigModel):
  File "/data/llmodel/miniconda3/envs/lmflow/lib/python3.9/site-packages/pydantic/_internal/_model_construction.py", line 171, in __new__
    set_model_fields(cls, bases, config_wrapper, types_namespace)
  File "/data/llmodel/miniconda3/envs/lmflow/lib/python3.9/site-packages/pydantic/_internal/_model_construction.py", line 361, in set_model_fields
    fields, class_vars = collect_model_fields(cls, bases, config_wrapper, types_namespace, typevars_map=typevars_map)
  File "/data/llmodel/miniconda3/envs/lmflow/lib/python3.9/site-packages/pydantic/_internal/_fields.py", line 112, in collect_model_fields
    raise NameError(f'Field "{ann_name}" has conflict with protected namespace "{protected_namespace}"')
NameError: Field "model_persistence_threshold" has conflict with protected namespace "model_"

**Comment by alphanlp** [comment]
deepspeed_args="--num_gpus=4 --master_port=11000"      # Default argument
if [ $# -ge 1 ]; then
  deepspeed_args="$1"
fi

exp_id=finetune
project_dir=$(cd "$(dirname $0)"/..; pwd)
output_dir=${project_dir}/output_models/${exp_id}
log_dir=${project_dir}/log/${exp_id}

dataset_path=${project_dir}/data/lmflow_data.json

mkdir -p ${output_dir} ${log_dir}

deepspeed ${deepspeed_args} \
  examples/finetune.py \
    --model_name_or_path  Ziya-LLaMA-13B-Pretrain-v1-merged \
    --dataset_path ${dataset_path} \
    --output_dir ${output_dir} --overwrite_output_dir \
    --num_train_epochs 0.01 \
    --learning_rate 2e-5 \
    --block_size 1024 \
    --per_device_train_batch_size 1 \
    --deepspeed configs/ds_config_zero3.json \
    --bf16 \
    --run_name finetune \
    --validation_split_percentage 0 \
    --logging_steps 20 \
    --do_train \
    --ddp_timeout 72000 \
    --save_steps 5000 \
    --dataloader_num_workers 1 \
    | tee ${log_dir}/train.log \
    2> ${log_dir}/train.err

**Comment by alphanlp** [comment]
i haven found the reason.

re install pydantic==1.10.7:
PS: after manually switch pydantic version from 2.0a2 to 1.10.7. the latest code works.
I have a quick glance on that, it's because pydantic 2.0a2 has removed __field__ attributes in BaseModel.

**Comment by GuaiYiHu** [comment]
> i haven found the reason.
> 
> re install pydantic==1.10.7: PS: after manually switch pydantic version from 2.0a2 to 1.10.7. the latest code works. I have a quick glance on that, it's because pydantic 2.0a2 has removed **field** attributes in BaseModel.

thanks

**Comment by laowangzi** [comment]
> i haven found the reason.
> 
> re install pydantic==1.10.7: PS: after manually switch pydantic version from 2.0a2 to 1.10.7. the latest code works. I have a quick glance on that, it's because pydantic 2.0a2 has removed **field** attributes in BaseModel.

Resolved. Thanks
