### ISSUE TITLE
Finetune the ChatGLM but raise errors.

### ISSUE THREAD

**Issue by seulgz** [OptimalScale/LMFlow#588]
I have referred to existing solutions in other issues. 
But got "ValueError: 130000 is not in list". 
What's going on? Thanks.

Traceback (most recent call last):
  File "/data1/lgz/Finetune/LMFlow/examples/finetune.py", line 61, in <module>
    main()
  File "/data1/lgz/Finetune/LMFlow/examples/finetune.py", line 57, in main
    tuned_model = finetuner.tune(model=model, dataset=dataset)
  File "/data1/lgz/Finetune/LMFlow/src/lmflow/pipeline/finetuner.py", line 285, in tune
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/data1/lgz/Finetune/Packages/transformers-c612628045822f909020f7eb6784c79700813eda/src/transformers/trainer.py", line 1639, in train
    return inner_training_loop(
  File "/data1/lgz/Finetune/Packages/transformers-c612628045822f909020f7eb6784c79700813eda/src/transformers/trainer.py", line 1906, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/data1/lgz/Finetune/Packages/transformers-c612628045822f909020f7eb6784c79700813eda/src/transformers/trainer.py", line 2652, in training_step
    loss = self.compute_loss(model, inputs)
  File "/data1/lgz/Finetune/Packages/transformers-c612628045822f909020f7eb6784c79700813eda/src/transformers/trainer.py", line 2684, in compute_loss
    outputs = model(**inputs)
  File "/data1/.conda/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data1/.conda/lmflow/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/data1/.conda/lmflow/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1846, in forward
    loss = self.module(*inputs, **kwargs)
  File "/data1/.conda/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/data1/lgz/Finetune/Packages/peft-deff03f2c251534fffd2511fc2d440e84cc54b1b/src/peft/peft_model.py", line 575, in forward
    return self.base_model(
  File "/data1/.conda/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/kgcode/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/619e736c6d4cd139840579c5482063b75bed5666/modeling_chatglm.py", line 1190, in forward
    transformer_outputs = self.transformer(
  File "/data1/.conda/lmflow/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/kgcode/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b/619e736c6d4cd139840579c5482063b75bed5666/modeling_chatglm.py", line 950, in forward
    mask_positions.append(seq.index(mask_token))
ValueError: 130000 is not in list
[2023-08-03 18:05:20,753] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 3917686
[2023-08-03 18:05:20,755] [ERROR] [launch.py:324:sigkill_handler] ['/data1/.conda/lmflow/bin/python', '-u', 'examples/finetune.py', '--local_rank=0', '--model_name_or_path', 'THUDM/chatglm-6b', '--dataset_path', '/data1/lgz/Finetune/LMFlow/data/b21b2', '--output_dir', '/data1/lgz/Finetune/LMFlow/output_models/finetune_with_lora', '--overwrite_output_dir', '--num_train_epochs', '2', '--learning_rate', '1e-4', '--block_size', '512', '--per_device_train_batch_size', '2', '--use_lora', '1', '--lora_r', '8', '--save_aggregated_lora', '0', '--deepspeed', 'configs/ds_config_zero3.json', '--bf16', '--run_name', 'finetune_with_lora', '--validation_split_percentage', '0', '--logging_steps', '20', '--do_train', '--ddp_timeout', '72000', '--save_steps', '10000', '--dataloader_num_workers', '1'] exits with return code = 1

**Comment by shizhediao** [comment]
Hi,
Currently, LMFlow supports `chatglm2` instead of `chatglm`. If needed, you might want to try `chatglm2`. 
Thanks!

**Comment by seulgz** [comment]
Thank you.
