### ISSUE TITLE
ValueError: Tokenizer class BaichuanTokenizer does not exist or is not currently imported.

### ISSUE THREAD

**Issue by gllary** [OptimalScale/LMFlow#619]
有没有好心的大佬可以解答一下疑惑，咱们这个框架是不支持baichuan嘛，因为我跑的时候遇到了这个问题ValueError: Tokenizer class BaichuanTokenizer does not exist or is not currently imported.

**Comment by shizhediao** [comment]
是支持的，可以试一下最新代码，如果有问题欢迎继续交流，谢谢

----
It's supported. You can give the latest code a try. If you encounter any issues, feel free to continue the discussion. Thank you.

**Comment by shizhediao** [comment]
This issue has been marked as stale because it has not had recent activity. If you think this still needs to be addressed please feel free to reopen this issue. Thanks

**Comment by oldunclez** [comment]
我用main的代码来跑也是提示这个错误

**Comment by research4pan** [comment]
I think it is because Baichuan uses a remote tokenizer, as according to this issue (https://github.com/baichuan-inc/Baichuan2/issues/135). As a solution, you may use `--trust_remote_code 1` option to turn on remote code trust, and add this argument to the following line.

https://github.com/OptimalScale/LMFlow/blob/main/src/lmflow/models/hf_decoder_model.py#L152

Hope that solves your issue 🙏

**Comment by mawenju203** [comment]
@shizhediao I also encountered the same problem, my version is 4.36.2; I'm using the latest code from baichuan2-7b-main.

**Comment by oldunclez** [comment]
> @shizhediao I also encountered the same problem, my version is 4.36.2; I'm using the latest code from baichuan2-7b-main.

you should add `--trust_remote_code 1` into `scripts/run_finetune_with_lora.sh`

![image](https://github.com/OptimalScale/LMFlow/assets/6986430/f1a37fa0-590c-4b66-9895-ad293ba0dcd6)

but in my case , it will thow another error:

```txt
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████| 2/2 [01:19<00:00, 39.51s/it]
Traceback (most recent call last):
  File "/app/LMFlow/examples/finetune.py", line 61, in <module>
    main()
  File "/app/LMFlow/examples/finetune.py", line 54, in main
    model = AutoModel.get_model(model_args)
  File "/app/LMFlow/src/lmflow/models/auto_model.py", line 16, in get_model
    return HFDecoderModel(model_args, *args, **kwargs)
  File "/app/LMFlow/src/lmflow/models/hf_decoder_model.py", line 330, in __init__
    model = get_peft_model(model, peft_config)
  File "/usr/local/lib/python3.10/site-packages/peft/mapping.py", line 116, in get_peft_model
    return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](model, peft_config, adapter_name=adapter_name)
  File "/usr/local/lib/python3.10/site-packages/peft/peft_model.py", line 947, in __init__
    super().__init__(model, peft_config, adapter_name)
  File "/usr/local/lib/python3.10/site-packages/peft/peft_model.py", line 119, in __init__
    self.base_model = cls(model, {adapter_name: peft_config}, adapter_name)
  File "/usr/local/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 111, in __init__
    super().__init__(model, config, adapter_name)
  File "/usr/local/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 93, in __init__
    self.inject_adapter(self.model, adapter_name)
  File "/usr/local/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 217, in inject_adapter
    peft_config = self._prepare_adapter_config(peft_config, model_config)
  File "/usr/local/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 373, in _prepare_adapter_config
    raise ValueError("Please specify `target_modules` in `peft_config`")
ValueError: Please specify `target_modules` in `peft_config`
[2024-01-25 10:10:25,445] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 1752
[2024-01-25 10:10:25,446] [ERROR] [launch.py:321:sigkill_handler] ['/usr/local/bin/python', '-u', 'examples/finetune.py', '--local_rank=0', '--trust_remote_code', '1', '--model_name_or_path', '/tmp/Baichuan2-7B-Chat', '--dataset_path', '/tmp/data/wiki_cn/', '--output_dir', 'output_models/Baichuan2-7B-Chat', '--overwrite_output_dir', '--num_train_epochs', '3', '--learning_rate', '1e-4', '--block_size', '512', '--per_device_train_batch_size', '1', '--use_lora', '1', '--lora_r', '8', '--save_aggregated_lora', '0', '--deepspeed', 'configs/ds_config_zero2.json', '--fp16', '--run_name', 'finetune_with_lora', '--validation_split_percentage', '0', '--logging_steps', '20', '--do_train', '--ddp_timeout', '72000', '--save_steps', '5000', '--dataloader_num_workers', '1'] exits with return code = 1
```

**Comment by shizhediao** [comment]
> I think it is because Baichuan uses a remote tokenizer, as according to this issue ([baichuan-inc/Baichuan2#135](https://github.com/baichuan-inc/Baichuan2/issues/135)). As a solution, you may use `--trust_remote_code 1` option to turn on remote code trust, and add this argument to the following line:
> 
> https://github.com/OptimalScale/LMFlow/blob/main/src/lmflow/models/hf_decoder_model.py#L152
> 
> Hope that solves your issue 🙏

Hi @mawenju203 Please refer to this solution.

**Comment by shizhediao** [comment]
> ```
> ValueError: Please specify `target_modules` in `peft_config`
> ```

As the error suggests, you will need to specify target_modules.  Take a look at this: https://stackoverflow.com/questions/76768226/target-modules-for-applying-peft-lora-on-different-models

**Comment by oldunclez** [comment]
> > ```
> > ValueError: Please specify `target_modules` in `peft_config`
> > ```
> 
> As the error suggests, you will need to specify target_modules. Take a look at this: https://stackoverflow.com/questions/76768226/target-modules-for-applying-peft-lora-on-different-models

Thank you . I have read this issue https://github.com/OptimalScale/LMFlow/issues/655#issuecomment-1772010562  , and it works
