### ISSUE TITLE
service/app.py could not start on Mac OS system

### ISSUE THREAD

**Issue by clarkchen900** [OptimalScale/LMFlow#64]
Here is the message after run python3.9 app.py in the service directory:
Seems the AutoModel module used "hostname -I" to determine the hostname, but this command option is not available on Mac OS system. Instead, "hostname -f" should be used.

===
Failed to use RAM optimized load. Automatically use original load instead.
[2023-04-02 18:56:51,278] [INFO] [comm.py:634:init_distributed] Not using the DeepSpeed or dist launchers, attempting to detect MPI environment...
hostname: illegal option -- I
usage: hostname [-fs] [name-of-host]
Traceback (most recent call last):
  File "/Users/clark/Source/Github/LMFlow/service/app.py", line 34, in <module>
    model = AutoModel.get_model(model_args, tune_strategy='none', ds_config=ds_config)
  File "/Users/clark/Source/Github/LMFlow/src/lmflow/models/auto_model.py", line 14, in get_model
    return HFDecoderModel(model_args, *args, **kwargs)
  File "/Users/clark/Source/Github/LMFlow/src/lmflow/models/hf_decoder_model.py", line 223, in __init__
    deepspeed.init_distributed()
  File "/Users/clark/Source/Github/lm_env/lib/python3.9/site-packages/deepspeed/comm/comm.py", line 642, in init_distributed
    mpi_discovery(distributed_port=distributed_port, verbose=verbose)
  File "/Users/clark/Source/Github/lm_env/lib/python3.9/site-packages/deepspeed/comm/comm.py", line 672, in mpi_discovery
    result = subprocess.check_output(hostname_cmd, shell=True)
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['hostname -I']' returned non-zero exit status 1.

**Comment by research4pan** [comment]
Thanks for your attention! Currently our support for Mac OS system is not fully tested yet, so you may encounter errors like that. You may try on other Linux machines, or Google Colab first. We will let you know once our Mac OS version is available. Thanks 😄

**Comment by JohnDuncan5171** [comment]
> Thanks for your attention! Currently our support for Mac OS system is not fully tested yet, so you may encounter errors like that. You may try on other Linux machines, or Google Colab first. We will let you know once our Mac OS version is available. Thanks 😄

*** please add this tip to README.md ***

My MacBook Pro m1 machine's log
``` 
[2023-04-04 15:48:08,471] [WARNING] [runner.py:186:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
Detected CUDA_VISIBLE_DEVICES=0: setting --include=localhost:0
Traceback (most recent call last):
  File "/opt/homebrew/bin/deepspeed", line 6, in <module>
    main()
  File "/opt/homebrew/lib/python3.9/site-packages/deepspeed/launcher/runner.py", line 411, in main
    raise RuntimeError("Unable to proceed, no GPU resources available")
RuntimeError: Unable to proceed, no GPU resources available
```

**Comment by research4pan** [comment]
We've added the corresponding notes in the [setup section of our README](https://github.com/OptimalScale/LMFlow#1setup). Thanks for your suggestion! 😄
