### ISSUE TITLE
[BUG]'RaftTrainer' object has no attribute 'accelerator'

### ISSUE THREAD

**Issue by Yummy813** [OptimalScale/LMFlow#644]
Traceback (most recent call last):
  File "/LMFlow/examples/raft_align.py", line 217, in <module>
    main()
  File "/LMFlow/examples/raft_align.py", line 208, in main
    aligned_model = aligner.align(
  File "/LMFlow/src/lmflow/pipeline/raft_aligner.py", line 616, in align
    raft_trainer.train(resume_from_checkpoint=False, is_first_time=True)
  File "/LMFlow/src/lmflow/pipeline/utils/raft_trainer.py", line 1600, in train
    return inner_training_loop1(
  File "/LMFlow/src/lmflow/pipeline/utils/raft_trainer.py", line 2021, in _inner_training_loop
    deepspeed_engine, optimizer, lr_scheduler = deepspeed_init(
  File "/venv/lib/python3.9/site-packages/transformers/deepspeed.py", line 340, in deepspeed_init
    hf_deepspeed_config = trainer.accelerator.state.deepspeed_plugin.hf_ds_config
AttributeError: 'RaftTrainer' object has no attribute 'accelerator'

**Comment by hendrydong** [comment]
Can you double check the pkgs with requirements.txt?
