### ISSUE TITLE
how to run the  download model with cmd and web service 

### ISSUE THREAD

**Issue by alexhmyang** [OptimalScale/LMFlow#67]
i have finished transfer llama 7b model to  llama-7b-hf (following 4.1 LLaMA Checkpoint )

now how  to run the  llama 7b model with web service and cmd? 

I tried to change the path in app.py , but it points to the huggingface url ( which i wish to point to my local model path)

![Screenshot from 2023-04-03 11-39-44](https://user-images.githubusercontent.com/10215059/229406861-2c6ca41e-fd62-4399-9b40-7dd3d386e029.png)
![Screenshot from 2023-04-03 11-46-26](https://user-images.githubusercontent.com/10215059/229406921-4ae63d53-7332-442d-a3aa-ae59d52cddf8.png)

cd ./service python app.py

medical model checkpoints

**Comment by SHUMKASHUN** [comment]
Hi, 
According to your figure 2, the `model_name_or_path' are still gpt2. Simply change it to the path to your converted llama checkpoint dir. 
Also, change your line 30 to the following to load the lora model.
```python
model_args = ModelArguments(model_name_or_path = model_name_or_path, lora_model_path = lora_path)
```

**Comment by alexhmyang** [comment]
> ```python
> lora_model_path
> ```

thank you! I follow your step, it moves on, but raise new issue.




(lmflow) u20@u20:~/LMFlow/service$ python app.py 
Loading checkpoint shards: 100%|██████████████████| 2/2 [00:21<00:00, 10.81s/it]
Traceback (most recent call last):
  File "/home/u20/LMFlow/service/app.py", line 36, in <module>
    model = AutoModel.get_model(model_args, tune_strategy='none', ds_config=ds_config)
  File "/home/u20/LMFlow/src/lmflow/models/auto_model.py", line 14, in get_model
    return HFDecoderModel(model_args, *args, **kwargs)
  File "/home/u20/LMFlow/src/lmflow/models/hf_decoder_model.py", line 192, in __init__
    self.backend_model = PeftModel.from_pretrained(
  File "/home/u20/miniconda3/envs/lmflow/lib/python3.9/site-packages/peft/peft_model.py", line 177, in from_pretrained
    model = dispatch_model(model, device_map=device_map)
  File "/home/u20/miniconda3/envs/lmflow/lib/python3.9/site-packages/accelerate/big_modeling.py", line 342, in dispatch_model
    raise ValueError(
ValueError: We need an `offload_dir` to dispatch this model according to this `device_map`, the following submodules need to be offloaded: base_model.model.model.layers.22, base_model.model.model.layers.23, base_model.model.model.layers.24, base_model.model.model.layers.25, base_model.model.model.layers.26, base_model.model.model.layers.27, base_model.model.model.layers.28, base_model.model.model.layers.29, base_model.model.model.layers.30, base_model.model.model.layers.31, base_model.model.model.norm, base_model.model.lm_head.


after google,  the answer may be this : https://github.com/oobabooga/text-generation-webui/issues/383
is it because my llama7b is original model is too large and without quantize and compressed? 

do you have a solution for this? thank you

**Comment by research4pan** [comment]
Thanks for your attention! Currently LoRA model doesn't support ram-optimized load (which offloads parameters to disks during loading). You can try to add `--use_ram_optimized_load False` to disable it and check if it works. Thanks 😄

**Comment by shizhediao** [comment]
This issue has been marked as stale because it has not had recent activity. If you think this still needs to be addressed please feel free to reopen this issue. Thanks 😄
