### ISSUE TITLE
[BUG] main branch deepspeed error report

### ISSUE THREAD

**Issue by Yummy416** [OptimalScale/LMFlow#686]
Hello, when I use your latest main branch to run SFT training, I get the following error. What’s going on?

Traceback (most recent call last):
  File "/LMFlow/src/lmflow/models/hf_decoder_model.py", line 284, in __init__
    model = AutoModelForCausalLM.from_pretrained(
  File "/venv/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 558, in from_pretrained
    return model_class.from_pretrained(
  File "/venv/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2445, in from_pretrained
    raise ValueError(
ValueError: DeepSpeed Zero-3 is not compatible with `low_cpu_mem_usage=True` or with passing a `device_map`.

**Comment by research4pan** [comment]
Thanks for your interest in LMFlow! Deepspeed zero-3 requires offload, which moves part of the model to CPU RAM, thus it is not compatible with `low_cpu_mem_usage`. We will arrange a fix in the future and let you know once it is done. Thanks very much for your understanding 😄
