### ISSUE TITLE
multi-gpu & batch inference

### ISSUE THREAD

**Issue by pckennethma** [OptimalScale/LMFlow#69]
Hello,

Could you consider add multi-gpu inference support to the codebase? DeepSpeed should have provided an [interface](https://www.deepspeed.ai/tutorials/inference-tutorial/) to this functionality. But I met some errors when adapting the code snippet in `hf_decoder_model.py`. 

Besides, the inference code in `examples/chatbot.py` can only take one input at a time. Is it possible to allow batch inference?

Thanks!

**Comment by shizhediao** [comment]
Hi,
Thank you for your suggestion!
It is easy to apply deepspeed inference. Please take a look at this [branch](https://github.com/OptimalScale/LMFlow/tree/shizhe-deepspeed-inf).

Actually, we implemented it before but did not find time to merge it to the main branch. Before merging, we need a lot of testing. We would appreciate it if you could help test this branch, especially the effects of applying it.

As for batch inference, we are implementing it these days. Will release it soon.

Thanks!

**Comment by shizhediao** [comment]
yes, I only test it on llama.
For other models, you can easily find `inject_policy` and apply them.
Welcome to contribute this repo. Thank you!

**Comment by pckennethma** [comment]
We have implemented a workaround to support multi-gpu batch inference (credit to @Jerry00917). [multigpu_infer.sh](https://github.com/pckennethma/LMFlow/blob/main/service/multigpu_infer.sh)

**Comment by shizhediao** [comment]
Hi,
Big thanks for your efforts @pckennethma and @Jerry00917.
I will review it soon.

**Comment by shizhediao** [comment]
Hi,
@pckennethma and @Jerry00917
Do you guys want to open a PR? Thank you so much for your great work.

**Comment by pckennethma** [comment]
We implement multi-gpu and batch inference with some dirty hacks. The batch inference code works good on GPT-Neo but has wired problem on llama. The script for multi-gpu works good for all models (as long as the GPU memory is enough for loading the entire model). You may take a look and see if it is suitable for merging to the main branch. If it is the case, we are happy to create a PR.

**Comment by shizhediao** [comment]
OK I see.
I will take a look and try to merge your code and modify it based on your branch.

Thanks

**Comment by Jerry00917** [comment]
Hello,
@shizhediao 

Currently, we are using the  deepspeed --num_gpu=4 command aiming to run multi-gpu infering, and  we have successfully implemented the multi-batch inference simply by using the batch_encode_plus method: 

prompt_all = model.tokenizer.batch_encode_plus(tuple(prompt), pad_to_max_length=True)

However, after converting the token into the localrank cuda, 

prompt_all = torch.tensor(prompt_all,dtype=torch.long,device=device)
outputs = model.inference(prompt_all, max_new_tokens=250,temperature=0.9, do_sample=False)

The "cuda not on the same device error" keeps occurring. However, I have checked many times that those tensors are in their correct cuda rank.


RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument index in method wrapper_CUDA__index_select)
  0%|                                                                                                                                                                                                                | 0/1996 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/root/LMFlow/service/serve_shard_ds.py", line 177, in <module>
    total_ans.extend(inference_many(model,cur,cuda0))
  File "/root/LMFlow/service/serve_shard_ds.py", line 64, in inference_many
    outputs = model.inference(prompt_all, max_new_tokens=250,temperature=0.9, do_sample=False)
  File "/root/LMFlow/src/lmflow/models/hf_decoder_model.py", line 383, in inference
    outputs = self.ds_engine.module.generate(
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/generation/utils.py", line 1437, in generate
    return self.greedy_search(
  File "/opt/conda/lib/python3.10/site-packages/transformers/generation/utils.py", line 2248, in greedy_search
    outputs = self(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/gpt_neo/modeling_gpt_neo.py", line 741, in forward
    transformer_outputs = self.transformer(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/gpt_neo/modeling_gpt_neo.py", line 621, in forward
    outputs = block(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/gpt_neo/modeling_gpt_neo.py", line 325, in forward
    hidden_states = self.ln_1(hidden_states)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/normalization.py", line 190, in forward
    return F.layer_norm(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/functional.py", line 2515, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument weight in method wrapper_CUDA__native_layer_norm)

**Comment by shizhediao** [comment]
Hi,
@yaoguany helped implement a multi-batch version and it passes the test on llama.
You might want to take a look https://github.com/OptimalScale/LMFlow/pull/153

**Comment by shizhediao** [comment]
Hi,
We have supported multi-gpu & batch inference in our main branch.
Please check it out.
Thank you!

**Comment by pckennethma** [comment]
Cool! Thanks a lot for your nice work!
