### ISSUE TITLE
About the use of chatbot.sh

### ISSUE THREAD

**Issue by HCShi** [OptimalScale/LMFlow#87]
Hi, when I download the opened model and use ./scripts/run_chatbot.sh model_path, I obtain the following error:
`ValueError: weight is on the meta device, we need a value to put in on 1.`
I do not find the solutions about this problem, could you please help to solve the problem?

**Comment by SHUMKASHUN** [comment]
Could you provide more information about which model you are using and paste the whole error message so that we can better understand your case ? Thank you.

**Comment by HCShi** [comment]
Hi, I am using the `llama13b-lora-medical` model, and the command is `./scripts/run_chatbot.sh ./output_models/llama13b-lora-medical/`.
The following is the logs.

`[2023-04-03 07:48:54,965] [WARNING] [runner.py:186:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.`
`Detected CUDA_VISIBLE_DEVICES=0: setting --include=localhost:0`
`[2023-04-03 07:48:54,977] [INFO] [runner.py:550:main] cmd = /home/anaconda3/envs/lmflow/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None examples/chatbot.py --deepspeed configs/ds_config_chatbot.json --model_name_or_path ./output_models/llama13b-lora-medical/`
`[2023-04-03 07:48:56,500] [INFO] [launch.py:142:main] WORLD INFO DICT: {'localhost': [0]}`
`[2023-04-03 07:48:56,500] [INFO] [launch.py:148:main] nnodes=1, num_local_procs=1, node_rank=0`
`[2023-04-03 07:48:56,500] [INFO] [launch.py:161:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})`
`[2023-04-03 07:48:56,500] [INFO] [launch.py:162:main] dist_world_size=1`
`[2023-04-03 07:48:56,500] [INFO] [launch.py:164:main] Setting CUDA_VISIBLE_DEVICES=0`
`Traceback (most recent call last):`
```
  File "/media/DATA/LMFlow-main/examples/chatbot.py", line 117, in <module>
    main()
  File "/media/DATA/LMFlow-main/examples/chatbot.py", line 44, in main
    model = AutoModel.get_model(
  File "/media/DATA/LMFlow-main/src/lmflow/models/auto_model.py", line 14, in get_model
    return HFDecoderModel(model_args, *args, **kwargs)
  File "/media/DATA/LMFlow-main/src/lmflow/models/hf_decoder_model.py", line 183, in __init__
    self.backend_model = AutoModelForCausalLM.from_pretrained(
  File "/home/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "/home/anaconda3/envs/lmflow/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2760, in from_pretrained
    dispatch_model(model, device_map=device_map, offload_dir=offload_folder, offload_index=offload_index)
  File "/home/anaconda3/envs/lmflow/lib/python3.9/site-packages/accelerate/big_modeling.py", line 370, in dispatch_model
    attach_align_device_hook_on_blocks(
  File "/home/anaconda3/envs/lmflow/lib/python3.9/site-packages/accelerate/hooks.py", line 502, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(
  File "/home/anaconda3/envs/lmflow/lib/python3.9/site-packages/accelerate/hooks.py", line 502, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(
  File "/home/anaconda3/envs/lmflow/lib/python3.9/site-packages/accelerate/hooks.py", line 478, in attach_align_device_hook_on_blocks
    add_hook_to_module(module, hook)
  File "/home/anaconda3/envs/lmflow/lib/python3.9/site-packages/accelerate/hooks.py", line 155, in add_hook_to_module
    module = hook.init_hook(module)
  File "/home/anaconda3/envs/lmflow/lib/python3.9/site-packages/accelerate/hooks.py", line 251, in init_hook
    set_module_tensor_to_device(module, name, self.execution_device)
  File "/home/anaconda3/envs/lmflow/lib/python3.9/site-packages/accelerate/utils/modeling.py", line 136, in set_module_tensor_to_device
    raise ValueError(f"{tensor_name} is on the meta device, we need a `value` to put in on {device}.")
```
`ValueError: weight is on the meta device, we need a `value` to put in on 0.`
`[2023-04-03 07:49:03,517] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 431083`
`[2023-04-03 07:49:03,518] [ERROR] [launch.py:324:sigkill_handler] ['/home/anaconda3/envs/lmflow/bin/python', '-u', 'examples/chatbot.py', '--local_rank=0', '--deepspeed', 'configs/ds_config_chatbot.json', '--model_name_or_path', './output_models/llama13b-lora-medical/'] exits with return code = 1`

**Comment by research4pan** [comment]
Thanks for your attention. The LoRA model is a model diff between the finetuned model and original model. To run a llama-model with LoRA checkpoint, you may use the following command,
```sh
./scripts/run_chatbot.sh pinkmanlove/llama-13b-hf ./output_models/llama13b-lora-medical/
```
if the hardware allows. Thanks 😄

**Comment by HCShi** [comment]
Hi, I have tried the command, but I obtain the following errors, the config.json is really added in the directory.

```
Traceback (most recent call last):
  File "/home/anaconda3/envs/lmflow/lib/python3.9/site-packages/peft/utils/config.py", line 99, in from_pretrained
    config_file = hf_hub_download(pretrained_model_name_or_path, CONFIG_NAME)
  File "/home/anaconda3/envs/lmflow/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 112, in _inner_fn
    validate_repo_id(arg_value)
  File "/home/anaconda3/envs/lmflow/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 160, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': './output_models/llama13b-lora-medical/'. Use `repo_type` argument if needed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/Codes/LMFlow-main/examples/chatbot.py", line 117, in <module>
    main()
  File "/media/Codes/LMFlow-main/examples/chatbot.py", line 44, in main
    model = AutoModel.get_model(
  File "/media/Codes/LMFlow-main/src/lmflow/models/auto_model.py", line 14, in get_model
    return HFDecoderModel(model_args, *args, **kwargs)
  File "/media/Codes/LMFlow-main/src/lmflow/models/hf_decoder_model.py", line 192, in __init__
    self.backend_model = PeftModel.from_pretrained(
  File "/home/anaconda3/envs/lmflow/lib/python3.9/site-packages/peft/peft_model.py", line 135, in from_pretrained
    config = PEFT_TYPE_TO_CONFIG_MAPPING[PeftConfig.from_pretrained(model_id).peft_type].from_pretrained(model_id)
  File "/home/anaconda3/envs/lmflow/lib/python3.9/site-packages/peft/utils/config.py", line 101, in from_pretrained
    raise ValueError(f"Can't find config.json at '{pretrained_model_name_or_path}'")
ValueError: Can't find config.json at './output_models/llama13b-lora-medical/'
[2023-04-04 10:16:50,423] [INFO] [launch.py:318:sigkill_handler] Killing subprocess 437129
[2023-04-04 10:16:50,452] [ERROR] [launch.py:324:sigkill_handler] ['/home/anaconda3/envs/lmflow/bin/python', '-u', 'examples/chatbot.py', '--local_rank=0', '--deepspeed', 'configs/ds_config_chatbot.json', '--model_name_or_path', 'pinkmanlove/llama-13b-hf', '--lora_model_path', './output_models/llama13b-lora-medical/'] exits with return code = 1
```

**Comment by research4pan** [comment]
```
...
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': './output_models/llama13b-lora-medical/'. Use `repo_type` argument if needed.
...
```
Looks like the model accessed huggingface with a wrong model name. Could you please try
```
./scripts/run_chatbot.sh pinkmanlove/llama-13b-hf
```
and see if it works? If not, it could be caused by accessibility problem related to huggingface. In that case, you may download the `pinkmanlove/llama-13b-hf` model locally first, and then refer to the local path.

**Comment by HCShi** [comment]
Thanks a lot. I will try again.

**Comment by shizhediao** [comment]
This issue has been marked as stale because it has not had recent activity. If you think this still needs to be addressed please feel free to reopen this issue. Thanks 😄

**Comment by HCShi** [comment]
Thanks a lot!
