### ISSUE TITLE
[BUG] EvaluatorArguments,

### ISSUE THREAD

**Issue by Harshit-tech9** [OptimalScale/LMFlow#885]
Description:

I encountered an issue while running the script feedback_training_raft_t2t.py. The script fails with the following traceback:

Traceback (most recent call last):
  File "/hdd/harshit-space/Feedbacknmt/train_scripts/../src/feedback_training_raft_t2t.py", line 15, in <module>
    from lmflow.args import (
  File "/home/eztech/.pyenv/versions/feedbackmt/lib/python3.10/site-packages/lmflow/args.py", line 533, in <module>
    "evaluator": EvaluatorArguments,
NameError: name 'EvaluatorArguments' is not defined

Details:

The error occurs in the file lmflow/args.py at line 533, where EvaluatorArguments is referenced.
It seems that EvaluatorArguments is not defined or imported in lmflow/args.py, causing a NameError. 

Expected Behavior:

The script should run without errors related to undefined names.

Environment:

Python version: 3.10
lmflow version: (Include the version of lmflow you're using)
Operating System: (Include your OS and version)
Additional Information:

Please let me know if there are any additional details required. I would appreciate any guidance or fixes for this issue.

**Comment by research4pan** [comment]
Thanks for your suggestions! For RAFT scripts, the LMFlow version needs to be very low, such as `v0.0.4`. You may try downgrading LMFlow to see if the problem is resolved. We are currently working on integrating supports for higher-version supports for RAFT, and will get back to you once it is available. Thanks for your understanding 🙏
